// flow-typed signature: cb8cb66f84d4165bed684c35e7169ce2
// flow-typed version: <<STUB>>/asevented_v^0.4.6/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'asevented'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'asevented' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'asevented/asevented' {
  declare module.exports: any;
}

declare module 'asevented/asevented.min' {
  declare module.exports: any;
}

declare module 'asevented/examples/example3' {
  declare module.exports: any;
}

declare module 'asevented/test/asevented_test' {
  declare module.exports: any;
}

declare module 'asevented/test/vendor/jquery.min' {
  declare module.exports: any;
}

declare module 'asevented/test/vendor/phantomjs-runner' {
  declare module.exports: any;
}

declare module 'asevented/test/vendor/qunit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'asevented/asevented.js' {
  declare module.exports: $Exports<'asevented/asevented'>;
}
declare module 'asevented/asevented.min.js' {
  declare module.exports: $Exports<'asevented/asevented.min'>;
}
declare module 'asevented/examples/example3.js' {
  declare module.exports: $Exports<'asevented/examples/example3'>;
}
declare module 'asevented/test/asevented_test.js' {
  declare module.exports: $Exports<'asevented/test/asevented_test'>;
}
declare module 'asevented/test/vendor/jquery.min.js' {
  declare module.exports: $Exports<'asevented/test/vendor/jquery.min'>;
}
declare module 'asevented/test/vendor/phantomjs-runner.js' {
  declare module.exports: $Exports<'asevented/test/vendor/phantomjs-runner'>;
}
declare module 'asevented/test/vendor/qunit.js' {
  declare module.exports: $Exports<'asevented/test/vendor/qunit'>;
}
