// flow-typed signature: 749ed6e4c4bc31175dc44e802f1d7868
// flow-typed version: <<STUB>>/blueimp-file-upload_v^9.15.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blueimp-file-upload'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'blueimp-file-upload' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blueimp-file-upload/js/cors/jquery.postmessage-transport' {
  declare module.exports: any;
}

declare module 'blueimp-file-upload/js/cors/jquery.xdr-transport' {
  declare module.exports: any;
}

declare module 'blueimp-file-upload/js/jquery.fileupload-angular' {
  declare module.exports: any;
}

declare module 'blueimp-file-upload/js/jquery.fileupload-audio' {
  declare module.exports: any;
}

declare module 'blueimp-file-upload/js/jquery.fileupload-image' {
  declare module.exports: any;
}

declare module 'blueimp-file-upload/js/jquery.fileupload-jquery-ui' {
  declare module.exports: any;
}

declare module 'blueimp-file-upload/js/jquery.fileupload-process' {
  declare module.exports: any;
}

declare module 'blueimp-file-upload/js/jquery.fileupload-ui' {
  declare module.exports: any;
}

declare module 'blueimp-file-upload/js/jquery.fileupload-validate' {
  declare module.exports: any;
}

declare module 'blueimp-file-upload/js/jquery.fileupload-video' {
  declare module.exports: any;
}

declare module 'blueimp-file-upload/js/jquery.fileupload' {
  declare module.exports: any;
}

declare module 'blueimp-file-upload/js/jquery.iframe-transport' {
  declare module.exports: any;
}

declare module 'blueimp-file-upload/js/vendor/jquery.ui.widget' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blueimp-file-upload/js/cors/jquery.postmessage-transport.js' {
  declare module.exports: $Exports<'blueimp-file-upload/js/cors/jquery.postmessage-transport'>;
}
declare module 'blueimp-file-upload/js/cors/jquery.xdr-transport.js' {
  declare module.exports: $Exports<'blueimp-file-upload/js/cors/jquery.xdr-transport'>;
}
declare module 'blueimp-file-upload/js/jquery.fileupload-angular.js' {
  declare module.exports: $Exports<'blueimp-file-upload/js/jquery.fileupload-angular'>;
}
declare module 'blueimp-file-upload/js/jquery.fileupload-audio.js' {
  declare module.exports: $Exports<'blueimp-file-upload/js/jquery.fileupload-audio'>;
}
declare module 'blueimp-file-upload/js/jquery.fileupload-image.js' {
  declare module.exports: $Exports<'blueimp-file-upload/js/jquery.fileupload-image'>;
}
declare module 'blueimp-file-upload/js/jquery.fileupload-jquery-ui.js' {
  declare module.exports: $Exports<'blueimp-file-upload/js/jquery.fileupload-jquery-ui'>;
}
declare module 'blueimp-file-upload/js/jquery.fileupload-process.js' {
  declare module.exports: $Exports<'blueimp-file-upload/js/jquery.fileupload-process'>;
}
declare module 'blueimp-file-upload/js/jquery.fileupload-ui.js' {
  declare module.exports: $Exports<'blueimp-file-upload/js/jquery.fileupload-ui'>;
}
declare module 'blueimp-file-upload/js/jquery.fileupload-validate.js' {
  declare module.exports: $Exports<'blueimp-file-upload/js/jquery.fileupload-validate'>;
}
declare module 'blueimp-file-upload/js/jquery.fileupload-video.js' {
  declare module.exports: $Exports<'blueimp-file-upload/js/jquery.fileupload-video'>;
}
declare module 'blueimp-file-upload/js/jquery.fileupload.js' {
  declare module.exports: $Exports<'blueimp-file-upload/js/jquery.fileupload'>;
}
declare module 'blueimp-file-upload/js/jquery.iframe-transport.js' {
  declare module.exports: $Exports<'blueimp-file-upload/js/jquery.iframe-transport'>;
}
declare module 'blueimp-file-upload/js/vendor/jquery.ui.widget.js' {
  declare module.exports: $Exports<'blueimp-file-upload/js/vendor/jquery.ui.widget'>;
}
