// flow-typed signature: ff74cd18889bd9bbd0def93a1a85be52
// flow-typed version: <<STUB>>/bootstrap-switch_v3.3.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-switch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-switch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap-switch/dist/js/bootstrap-switch' {
  declare module.exports: any;
}

declare module 'bootstrap-switch/dist/js/bootstrap-switch.min' {
  declare module.exports: any;
}

declare module 'bootstrap-switch/docs/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'bootstrap-switch/docs/js/highlight' {
  declare module.exports: any;
}

declare module 'bootstrap-switch/docs/js/jquery.min' {
  declare module.exports: any;
}

declare module 'bootstrap-switch/docs/js/main' {
  declare module.exports: any;
}

declare module 'bootstrap-switch/gulpfile' {
  declare module.exports: any;
}

declare module 'bootstrap-switch/src/docs/js/highlight' {
  declare module.exports: any;
}

declare module 'bootstrap-switch/test/bootstrap-switch' {
  declare module.exports: any;
}

declare module 'bootstrap-switch/test/bootstrap-switch.tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap-switch/dist/js/bootstrap-switch.js' {
  declare module.exports: $Exports<'bootstrap-switch/dist/js/bootstrap-switch'>;
}
declare module 'bootstrap-switch/dist/js/bootstrap-switch.min.js' {
  declare module.exports: $Exports<'bootstrap-switch/dist/js/bootstrap-switch.min'>;
}
declare module 'bootstrap-switch/docs/js/bootstrap.min.js' {
  declare module.exports: $Exports<'bootstrap-switch/docs/js/bootstrap.min'>;
}
declare module 'bootstrap-switch/docs/js/highlight.js' {
  declare module.exports: $Exports<'bootstrap-switch/docs/js/highlight'>;
}
declare module 'bootstrap-switch/docs/js/jquery.min.js' {
  declare module.exports: $Exports<'bootstrap-switch/docs/js/jquery.min'>;
}
declare module 'bootstrap-switch/docs/js/main.js' {
  declare module.exports: $Exports<'bootstrap-switch/docs/js/main'>;
}
declare module 'bootstrap-switch/gulpfile.js' {
  declare module.exports: $Exports<'bootstrap-switch/gulpfile'>;
}
declare module 'bootstrap-switch/src/docs/js/highlight.js' {
  declare module.exports: $Exports<'bootstrap-switch/src/docs/js/highlight'>;
}
declare module 'bootstrap-switch/test/bootstrap-switch.js' {
  declare module.exports: $Exports<'bootstrap-switch/test/bootstrap-switch'>;
}
declare module 'bootstrap-switch/test/bootstrap-switch.tests.js' {
  declare module.exports: $Exports<'bootstrap-switch/test/bootstrap-switch.tests'>;
}
