// flow-typed signature: e7256456a4b5a1e60ea4a2b18ed781d7
// flow-typed version: <<STUB>>/bootstrap-colorpicker_v^2.5.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-colorpicker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-colorpicker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap-colorpicker/dist/js/bootstrap-colorpicker' {
  declare module.exports: any;
}

declare module 'bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min' {
  declare module.exports: any;
}

declare module 'bootstrap-colorpicker/docs/helpers/code/index' {
  declare module.exports: any;
}

declare module 'bootstrap-colorpicker/Gruntfile' {
  declare module.exports: any;
}

declare module 'bootstrap-colorpicker/serve' {
  declare module.exports: any;
}

declare module 'bootstrap-colorpicker/src/js/colorpicker-color' {
  declare module.exports: any;
}

declare module 'bootstrap-colorpicker/src/js/colorpicker-component' {
  declare module.exports: any;
}

declare module 'bootstrap-colorpicker/src/js/colorpicker-defaults' {
  declare module.exports: any;
}

declare module 'bootstrap-colorpicker/src/js/colorpicker-plugin-wrapper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap-colorpicker/dist/js/bootstrap-colorpicker.js' {
  declare module.exports: $Exports<'bootstrap-colorpicker/dist/js/bootstrap-colorpicker'>;
}
declare module 'bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js' {
  declare module.exports: $Exports<'bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min'>;
}
declare module 'bootstrap-colorpicker/docs/helpers/code/index.js' {
  declare module.exports: $Exports<'bootstrap-colorpicker/docs/helpers/code/index'>;
}
declare module 'bootstrap-colorpicker/Gruntfile.js' {
  declare module.exports: $Exports<'bootstrap-colorpicker/Gruntfile'>;
}
declare module 'bootstrap-colorpicker/serve.js' {
  declare module.exports: $Exports<'bootstrap-colorpicker/serve'>;
}
declare module 'bootstrap-colorpicker/src/js/colorpicker-color.js' {
  declare module.exports: $Exports<'bootstrap-colorpicker/src/js/colorpicker-color'>;
}
declare module 'bootstrap-colorpicker/src/js/colorpicker-component.js' {
  declare module.exports: $Exports<'bootstrap-colorpicker/src/js/colorpicker-component'>;
}
declare module 'bootstrap-colorpicker/src/js/colorpicker-defaults.js' {
  declare module.exports: $Exports<'bootstrap-colorpicker/src/js/colorpicker-defaults'>;
}
declare module 'bootstrap-colorpicker/src/js/colorpicker-plugin-wrapper.js' {
  declare module.exports: $Exports<'bootstrap-colorpicker/src/js/colorpicker-plugin-wrapper'>;
}
