// flow-typed signature: 137cff791f3e5d5dc6aaefc78e2b8890
// flow-typed version: <<STUB>>/breakpoint-sass_v^2.7.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'breakpoint-sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'breakpoint-sass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'breakpoint-sass/eyeglass-exports' {
  declare module.exports: any;
}

declare module 'breakpoint-sass/tests/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'breakpoint-sass/eyeglass-exports.js' {
  declare module.exports: $Exports<'breakpoint-sass/eyeglass-exports'>;
}
declare module 'breakpoint-sass/tests/index.js' {
  declare module.exports: $Exports<'breakpoint-sass/tests/index'>;
}
