// flow-typed signature: 44e61ab0e27ea73e1de3fc469686e7bc
// flow-typed version: <<STUB>>/chosen-js_v^1.6.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chosen-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'chosen-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chosen-js/chosen.jquery' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chosen-js/chosen.jquery.js' {
  declare module.exports: $Exports<'chosen-js/chosen.jquery'>;
}
