// flow-typed signature: 89452899d68c0f54756c3895f341b08d
// flow-typed version: <<STUB>>/coffeelint_v^1.16.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'coffeelint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'coffeelint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'coffeelint/lib/cache' {
  declare module.exports: any;
}

declare module 'coffeelint/lib/coffeelint' {
  declare module.exports: any;
}

declare module 'coffeelint/lib/commandline' {
  declare module.exports: any;
}

declare module 'coffeelint/lib/configfinder' {
  declare module.exports: any;
}

declare module 'coffeelint/lib/reporters/checkstyle' {
  declare module.exports: any;
}

declare module 'coffeelint/lib/reporters/csv' {
  declare module.exports: any;
}

declare module 'coffeelint/lib/reporters/default' {
  declare module.exports: any;
}

declare module 'coffeelint/lib/reporters/jslint' {
  declare module.exports: any;
}

declare module 'coffeelint/lib/reporters/raw' {
  declare module.exports: any;
}

declare module 'coffeelint/lib/ruleLoader' {
  declare module.exports: any;
}

declare module 'coffeelint/vowsrunner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'coffeelint/lib/cache.js' {
  declare module.exports: $Exports<'coffeelint/lib/cache'>;
}
declare module 'coffeelint/lib/coffeelint.js' {
  declare module.exports: $Exports<'coffeelint/lib/coffeelint'>;
}
declare module 'coffeelint/lib/commandline.js' {
  declare module.exports: $Exports<'coffeelint/lib/commandline'>;
}
declare module 'coffeelint/lib/configfinder.js' {
  declare module.exports: $Exports<'coffeelint/lib/configfinder'>;
}
declare module 'coffeelint/lib/reporters/checkstyle.js' {
  declare module.exports: $Exports<'coffeelint/lib/reporters/checkstyle'>;
}
declare module 'coffeelint/lib/reporters/csv.js' {
  declare module.exports: $Exports<'coffeelint/lib/reporters/csv'>;
}
declare module 'coffeelint/lib/reporters/default.js' {
  declare module.exports: $Exports<'coffeelint/lib/reporters/default'>;
}
declare module 'coffeelint/lib/reporters/jslint.js' {
  declare module.exports: $Exports<'coffeelint/lib/reporters/jslint'>;
}
declare module 'coffeelint/lib/reporters/raw.js' {
  declare module.exports: $Exports<'coffeelint/lib/reporters/raw'>;
}
declare module 'coffeelint/lib/ruleLoader.js' {
  declare module.exports: $Exports<'coffeelint/lib/ruleLoader'>;
}
declare module 'coffeelint/vowsrunner.js' {
  declare module.exports: $Exports<'coffeelint/vowsrunner'>;
}
