// flow-typed signature: 5368ea5efdc93df5bc8a52e972f476e6
// flow-typed version: <<STUB>>/cropper_v^1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cropper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cropper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cropper/dist/cropper' {
  declare module.exports: any;
}

declare module 'cropper/dist/cropper.min' {
  declare module.exports: any;
}

declare module 'cropper/src/js/bind' {
  declare module.exports: any;
}

declare module 'cropper/src/js/build' {
  declare module.exports: any;
}

declare module 'cropper/src/js/change' {
  declare module.exports: any;
}

declare module 'cropper/src/js/cropper' {
  declare module.exports: any;
}

declare module 'cropper/src/js/defaults' {
  declare module.exports: any;
}

declare module 'cropper/src/js/handlers' {
  declare module.exports: any;
}

declare module 'cropper/src/js/intro' {
  declare module.exports: any;
}

declare module 'cropper/src/js/load' {
  declare module.exports: any;
}

declare module 'cropper/src/js/methods' {
  declare module.exports: any;
}

declare module 'cropper/src/js/outro' {
  declare module.exports: any;
}

declare module 'cropper/src/js/plugin' {
  declare module.exports: any;
}

declare module 'cropper/src/js/preview' {
  declare module.exports: any;
}

declare module 'cropper/src/js/prototype' {
  declare module.exports: any;
}

declare module 'cropper/src/js/render' {
  declare module.exports: any;
}

declare module 'cropper/src/js/template' {
  declare module.exports: any;
}

declare module 'cropper/src/js/utilities' {
  declare module.exports: any;
}

declare module 'cropper/src/js/variables' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cropper/dist/cropper.js' {
  declare module.exports: $Exports<'cropper/dist/cropper'>;
}
declare module 'cropper/dist/cropper.min.js' {
  declare module.exports: $Exports<'cropper/dist/cropper.min'>;
}
declare module 'cropper/src/js/bind.js' {
  declare module.exports: $Exports<'cropper/src/js/bind'>;
}
declare module 'cropper/src/js/build.js' {
  declare module.exports: $Exports<'cropper/src/js/build'>;
}
declare module 'cropper/src/js/change.js' {
  declare module.exports: $Exports<'cropper/src/js/change'>;
}
declare module 'cropper/src/js/cropper.js' {
  declare module.exports: $Exports<'cropper/src/js/cropper'>;
}
declare module 'cropper/src/js/defaults.js' {
  declare module.exports: $Exports<'cropper/src/js/defaults'>;
}
declare module 'cropper/src/js/handlers.js' {
  declare module.exports: $Exports<'cropper/src/js/handlers'>;
}
declare module 'cropper/src/js/intro.js' {
  declare module.exports: $Exports<'cropper/src/js/intro'>;
}
declare module 'cropper/src/js/load.js' {
  declare module.exports: $Exports<'cropper/src/js/load'>;
}
declare module 'cropper/src/js/methods.js' {
  declare module.exports: $Exports<'cropper/src/js/methods'>;
}
declare module 'cropper/src/js/outro.js' {
  declare module.exports: $Exports<'cropper/src/js/outro'>;
}
declare module 'cropper/src/js/plugin.js' {
  declare module.exports: $Exports<'cropper/src/js/plugin'>;
}
declare module 'cropper/src/js/preview.js' {
  declare module.exports: $Exports<'cropper/src/js/preview'>;
}
declare module 'cropper/src/js/prototype.js' {
  declare module.exports: $Exports<'cropper/src/js/prototype'>;
}
declare module 'cropper/src/js/render.js' {
  declare module.exports: $Exports<'cropper/src/js/render'>;
}
declare module 'cropper/src/js/template.js' {
  declare module.exports: $Exports<'cropper/src/js/template'>;
}
declare module 'cropper/src/js/utilities.js' {
  declare module.exports: $Exports<'cropper/src/js/utilities'>;
}
declare module 'cropper/src/js/variables.js' {
  declare module.exports: $Exports<'cropper/src/js/variables'>;
}
