// flow-typed signature: 1de010e608356626cdf6da03ef54c4e3
// flow-typed version: <<STUB>>/custom-event-polyfill_v^0.3.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'custom-event-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'custom-event-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'custom-event-polyfill/custom-event-polyfill' {
  declare module.exports: any;
}

declare module 'custom-event-polyfill/karma.conf' {
  declare module.exports: any;
}

declare module 'custom-event-polyfill/tests/customevent.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'custom-event-polyfill/custom-event-polyfill.js' {
  declare module.exports: $Exports<'custom-event-polyfill/custom-event-polyfill'>;
}
declare module 'custom-event-polyfill/karma.conf.js' {
  declare module.exports: $Exports<'custom-event-polyfill/karma.conf'>;
}
declare module 'custom-event-polyfill/tests/customevent.test.js' {
  declare module.exports: $Exports<'custom-event-polyfill/tests/customevent.test'>;
}
