// flow-typed signature: fb370d6b9c2a466caafebc792fb2b41c
// flow-typed version: <<STUB>>/diff-match-patch_v^1.0.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'diff-match-patch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'diff-match-patch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'diff-match-patch/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'diff-match-patch/index' {
  declare module.exports: $Exports<'diff-match-patch'>;
}
declare module 'diff-match-patch/index.js' {
  declare module.exports: $Exports<'diff-match-patch'>;
}
declare module 'diff-match-patch/test/index.js' {
  declare module.exports: $Exports<'diff-match-patch/test/index'>;
}
