// flow-typed signature: 13005dfc73750b75af5c55c8b1b7f815
// flow-typed version: <<STUB>>/eonasdan-bootstrap-datetimepicker_v^4.17.46/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eonasdan-bootstrap-datetimepicker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eonasdan-bootstrap-datetimepicker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min' {
  declare module.exports: any;
}

declare module 'eonasdan-bootstrap-datetimepicker/docs/theme/js/base' {
  declare module.exports: any;
}

declare module 'eonasdan-bootstrap-datetimepicker/docs/theme/js/prettify-1.0.min' {
  declare module.exports: any;
}

declare module 'eonasdan-bootstrap-datetimepicker/Gruntfile' {
  declare module.exports: any;
}

declare module 'eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker' {
  declare module.exports: any;
}

declare module 'eonasdan-bootstrap-datetimepicker/tasks/bump_version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' {
  declare module.exports: $Exports<'eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min'>;
}
declare module 'eonasdan-bootstrap-datetimepicker/docs/theme/js/base.js' {
  declare module.exports: $Exports<'eonasdan-bootstrap-datetimepicker/docs/theme/js/base'>;
}
declare module 'eonasdan-bootstrap-datetimepicker/docs/theme/js/prettify-1.0.min.js' {
  declare module.exports: $Exports<'eonasdan-bootstrap-datetimepicker/docs/theme/js/prettify-1.0.min'>;
}
declare module 'eonasdan-bootstrap-datetimepicker/Gruntfile.js' {
  declare module.exports: $Exports<'eonasdan-bootstrap-datetimepicker/Gruntfile'>;
}
declare module 'eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js' {
  declare module.exports: $Exports<'eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker'>;
}
declare module 'eonasdan-bootstrap-datetimepicker/tasks/bump_version.js' {
  declare module.exports: $Exports<'eonasdan-bootstrap-datetimepicker/tasks/bump_version'>;
}
