// flow-typed signature: 77b9075ac93ee8d59805043069aa087c
// flow-typed version: <<STUB>>/gulp-rev-manifest-rails_v0.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-rev-manifest-rails'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-rev-manifest-rails' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-rev-manifest-rails/index' {
  declare module.exports: $Exports<'gulp-rev-manifest-rails'>;
}
declare module 'gulp-rev-manifest-rails/index.js' {
  declare module.exports: $Exports<'gulp-rev-manifest-rails'>;
}
