// flow-typed signature: 7f223185b4b489290dd5c61740119a72
// flow-typed version: <<STUB>>/gulp-rev-replace_v^0.4.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-rev-replace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-rev-replace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-rev-replace/test' {
  declare module.exports: any;
}

declare module 'gulp-rev-replace/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-rev-replace/index' {
  declare module.exports: $Exports<'gulp-rev-replace'>;
}
declare module 'gulp-rev-replace/index.js' {
  declare module.exports: $Exports<'gulp-rev-replace'>;
}
declare module 'gulp-rev-replace/test.js' {
  declare module.exports: $Exports<'gulp-rev-replace/test'>;
}
declare module 'gulp-rev-replace/utils.js' {
  declare module.exports: $Exports<'gulp-rev-replace/utils'>;
}
