// flow-typed signature: 2e1ce726bdcb1f9f179f9012c715ccbe
// flow-typed version: <<STUB>>/gulp-bump_v^2.7.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-bump'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-bump' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-bump/examples/gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-bump/test/errorCases' {
  declare module.exports: any;
}

declare module 'gulp-bump/test/fileFixtures' {
  declare module.exports: any;
}

declare module 'gulp-bump/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-bump/examples/gulpfile.js' {
  declare module.exports: $Exports<'gulp-bump/examples/gulpfile'>;
}
declare module 'gulp-bump/index' {
  declare module.exports: $Exports<'gulp-bump'>;
}
declare module 'gulp-bump/index.js' {
  declare module.exports: $Exports<'gulp-bump'>;
}
declare module 'gulp-bump/test/errorCases.js' {
  declare module.exports: $Exports<'gulp-bump/test/errorCases'>;
}
declare module 'gulp-bump/test/fileFixtures.js' {
  declare module.exports: $Exports<'gulp-bump/test/fileFixtures'>;
}
declare module 'gulp-bump/test/index.js' {
  declare module.exports: $Exports<'gulp-bump/test/index'>;
}
