// flow-typed signature: 3c0683b6315d68db80352b569bbc381d
// flow-typed version: <<STUB>>/gulp-if_v^2.0.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-if'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-if' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-if/index' {
  declare module.exports: $Exports<'gulp-if'>;
}
declare module 'gulp-if/index.js' {
  declare module.exports: $Exports<'gulp-if'>;
}
