// flow-typed signature: ef6b812015220e1fc40da2e7d2c9c9a3
// flow-typed version: <<STUB>>/gulp-coffee_v^2.3.4/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-coffee'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-coffee' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-coffee/test/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-coffee/index' {
  declare module.exports: $Exports<'gulp-coffee'>;
}
declare module 'gulp-coffee/index.js' {
  declare module.exports: $Exports<'gulp-coffee'>;
}
declare module 'gulp-coffee/test/main.js' {
  declare module.exports: $Exports<'gulp-coffee/test/main'>;
}
