// flow-typed signature: 8cafb30069cd0f74e98f14381eaeb2f3
// flow-typed version: <<STUB>>/gulp-cached_v^1.1.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-cached'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-cached' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-cached/test/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-cached/index' {
  declare module.exports: $Exports<'gulp-cached'>;
}
declare module 'gulp-cached/index.js' {
  declare module.exports: $Exports<'gulp-cached'>;
}
declare module 'gulp-cached/test/main.js' {
  declare module.exports: $Exports<'gulp-cached/test/main'>;
}
