// flow-typed signature: 3f67a012861050e991cf0a7bc1e438da
// flow-typed version: <<STUB>>/gulp-batch_v^1.0.5/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-batch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-batch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-batch/index' {
  declare module.exports: $Exports<'gulp-batch'>;
}
declare module 'gulp-batch/index.js' {
  declare module.exports: $Exports<'gulp-batch'>;
}
