// flow-typed signature: 44d3cc7e253f80fb55c45c2d049024c8
// flow-typed version: <<STUB>>/gulp-prettier_v^1.1.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-prettier/index' {
  declare module.exports: $Exports<'gulp-prettier'>;
}
declare module 'gulp-prettier/index.js' {
  declare module.exports: $Exports<'gulp-prettier'>;
}
