// flow-typed signature: 91cbe8d72ce62cbf3082482ef1ed9377
// flow-typed version: <<STUB>>/history.js_v^1.8.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'history.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'history.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'history.js/history.adapter.ender' {
  declare module.exports: any;
}

declare module 'history.js/history' {
  declare module.exports: any;
}

// Filename aliases
declare module 'history.js/history.adapter.ender.js' {
  declare module.exports: $Exports<'history.js/history.adapter.ender'>;
}
declare module 'history.js/history.js' {
  declare module.exports: $Exports<'history.js/history'>;
}
