// flow-typed signature: 33fd9507be7c688031acc6833b686b04
// flow-typed version: <<STUB>>/interact.js_v^1.2.8/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'interact.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'interact.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'interact.js/dist/interact' {
  declare module.exports: any;
}

declare module 'interact.js/dist/interact.min' {
  declare module.exports: any;
}

declare module 'interact.js/interact' {
  declare module.exports: any;
}

// Filename aliases
declare module 'interact.js/dist/interact.js' {
  declare module.exports: $Exports<'interact.js/dist/interact'>;
}
declare module 'interact.js/dist/interact.min.js' {
  declare module.exports: $Exports<'interact.js/dist/interact.min'>;
}
declare module 'interact.js/interact.js' {
  declare module.exports: $Exports<'interact.js/interact'>;
}
