// flow-typed signature: fd7b49b619607369fd9b0e26120d8573
// flow-typed version: <<STUB>>/javascript-autocomplete_v^1.0.3/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'javascript-autocomplete'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'javascript-autocomplete' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'javascript-autocomplete/auto-complete' {
  declare module.exports: any;
}

declare module 'javascript-autocomplete/auto-complete.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'javascript-autocomplete/auto-complete.js' {
  declare module.exports: $Exports<'javascript-autocomplete/auto-complete'>;
}
declare module 'javascript-autocomplete/auto-complete.min.js' {
  declare module.exports: $Exports<'javascript-autocomplete/auto-complete.min'>;
}
