// flow-typed signature: 904708eff0e852d2244ffc49f6a3da21
// flow-typed version: <<STUB>>/jquery-inview_v^1.1.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery-inview'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery-inview' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery-inview/jquery.inview' {
  declare module.exports: any;
}

declare module 'jquery-inview/jquery.inview.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery-inview/jquery.inview.js' {
  declare module.exports: $Exports<'jquery-inview/jquery.inview'>;
}
declare module 'jquery-inview/jquery.inview.min.js' {
  declare module.exports: $Exports<'jquery-inview/jquery.inview.min'>;
}
