// flow-typed signature: f70ba40b6762ccb4b641edb578289456
// flow-typed version: <<STUB>>/jquery.payment_v3.0.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery.payment'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery.payment' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery.payment/lib/jquery.payment' {
  declare module.exports: any;
}

declare module 'jquery.payment/lib/jquery.payment.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery.payment/lib/jquery.payment.js' {
  declare module.exports: $Exports<'jquery.payment/lib/jquery.payment'>;
}
declare module 'jquery.payment/lib/jquery.payment.min.js' {
  declare module.exports: $Exports<'jquery.payment/lib/jquery.payment.min'>;
}
