// flow-typed signature: f4c7826bee41ae3426c5fa9e03cb460d
// flow-typed version: <<STUB>>/jquery-jcrop_v^0.9.13/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery-jcrop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery-jcrop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery-jcrop/js/Jcrop' {
  declare module.exports: any;
}

declare module 'jquery-jcrop/js/jquery.color' {
  declare module.exports: any;
}

declare module 'jquery-jcrop/js/jquery.Jcrop' {
  declare module.exports: any;
}

declare module 'jquery-jcrop/js/jquery.Jcrop.min' {
  declare module.exports: any;
}

declare module 'jquery-jcrop/js/jquery.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery-jcrop/js/Jcrop.js' {
  declare module.exports: $Exports<'jquery-jcrop/js/Jcrop'>;
}
declare module 'jquery-jcrop/js/jquery.color.js' {
  declare module.exports: $Exports<'jquery-jcrop/js/jquery.color'>;
}
declare module 'jquery-jcrop/js/jquery.Jcrop.js' {
  declare module.exports: $Exports<'jquery-jcrop/js/jquery.Jcrop'>;
}
declare module 'jquery-jcrop/js/jquery.Jcrop.min.js' {
  declare module.exports: $Exports<'jquery-jcrop/js/jquery.Jcrop.min'>;
}
declare module 'jquery-jcrop/js/jquery.min.js' {
  declare module.exports: $Exports<'jquery-jcrop/js/jquery.min'>;
}
