// flow-typed signature: ec17bf930673ebd2d014292d4ccb0095
// flow-typed version: <<STUB>>/jquery.customSelect_v^0.5.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery.customSelect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery.customSelect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery.customSelect/jquery.customSelect' {
  declare module.exports: any;
}

declare module 'jquery.customSelect/jquery.customSelect.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery.customSelect/jquery.customSelect.js' {
  declare module.exports: $Exports<'jquery.customSelect/jquery.customSelect'>;
}
declare module 'jquery.customSelect/jquery.customSelect.min.js' {
  declare module.exports: $Exports<'jquery.customSelect/jquery.customSelect.min'>;
}
