// flow-typed signature: d06289a0aaf1cf8aa26214254a3df020
// flow-typed version: <<STUB>>/jquery.cookie_v^1.4.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery.cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery.cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery.cookie/Gruntfile' {
  declare module.exports: any;
}

declare module 'jquery.cookie/jquery.cookie' {
  declare module.exports: any;
}

declare module 'jquery.cookie/test/server' {
  declare module.exports: any;
}

declare module 'jquery.cookie/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery.cookie/Gruntfile.js' {
  declare module.exports: $Exports<'jquery.cookie/Gruntfile'>;
}
declare module 'jquery.cookie/jquery.cookie.js' {
  declare module.exports: $Exports<'jquery.cookie/jquery.cookie'>;
}
declare module 'jquery.cookie/test/server.js' {
  declare module.exports: $Exports<'jquery.cookie/test/server'>;
}
declare module 'jquery.cookie/test/tests.js' {
  declare module.exports: $Exports<'jquery.cookie/test/tests'>;
}
