// flow-typed signature: 694403f4ef549ce4b019e006a9873918
// flow-typed version: <<STUB>>/jquery-ui-touch-punch_v^0.2.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery-ui-touch-punch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery-ui-touch-punch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery-ui-touch-punch/jquery.ui.touch-punch' {
  declare module.exports: any;
}

declare module 'jquery-ui-touch-punch/jquery.ui.touch-punch.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery-ui-touch-punch/jquery.ui.touch-punch.js' {
  declare module.exports: $Exports<'jquery-ui-touch-punch/jquery.ui.touch-punch'>;
}
declare module 'jquery-ui-touch-punch/jquery.ui.touch-punch.min.js' {
  declare module.exports: $Exports<'jquery-ui-touch-punch/jquery.ui.touch-punch.min'>;
}
