// flow-typed signature: dfb8a86ee370a18c9ca295eb0930a3de
// flow-typed version: <<STUB>>/jquery-ujs_v^1.2.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery-ujs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery-ujs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery-ujs/src/rails' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery-ujs/src/rails.js' {
  declare module.exports: $Exports<'jquery-ujs/src/rails'>;
}
