// flow-typed signature: a17176bb2aaaff64868666a9bab6ae16
// flow-typed version: <<STUB>>/jstimezonedetect_v^1.0.6/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jstimezonedetect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jstimezonedetect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jstimezonedetect/dist/jstz' {
  declare module.exports: any;
}

declare module 'jstimezonedetect/dist/jstz.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jstimezonedetect/dist/jstz.js' {
  declare module.exports: $Exports<'jstimezonedetect/dist/jstz'>;
}
declare module 'jstimezonedetect/dist/jstz.min.js' {
  declare module.exports: $Exports<'jstimezonedetect/dist/jstz.min'>;
}
