// flow-typed signature: 038d97881643b939fb1db22c31093a43
// flow-typed version: <<STUB>>/jstree_v^3.3.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jstree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jstree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jstree/dist/jstree' {
  declare module.exports: any;
}

declare module 'jstree/dist/jstree.min' {
  declare module.exports: any;
}

declare module 'jstree/gruntfile' {
  declare module.exports: any;
}

declare module 'jstree/src/intro' {
  declare module.exports: any;
}

declare module 'jstree/src/jstree.changed' {
  declare module.exports: any;
}

declare module 'jstree/src/jstree.checkbox' {
  declare module.exports: any;
}

declare module 'jstree/src/jstree.conditionalselect' {
  declare module.exports: any;
}

declare module 'jstree/src/jstree.contextmenu' {
  declare module.exports: any;
}

declare module 'jstree/src/jstree.dnd' {
  declare module.exports: any;
}

declare module 'jstree/src/jstree' {
  declare module.exports: any;
}

declare module 'jstree/src/jstree.massload' {
  declare module.exports: any;
}

declare module 'jstree/src/jstree.search' {
  declare module.exports: any;
}

declare module 'jstree/src/jstree.sort' {
  declare module.exports: any;
}

declare module 'jstree/src/jstree.state' {
  declare module.exports: any;
}

declare module 'jstree/src/jstree.types' {
  declare module.exports: any;
}

declare module 'jstree/src/jstree.unique' {
  declare module.exports: any;
}

declare module 'jstree/src/jstree.wholerow' {
  declare module.exports: any;
}

declare module 'jstree/src/misc' {
  declare module.exports: any;
}

declare module 'jstree/src/outro' {
  declare module.exports: any;
}

declare module 'jstree/src/sample' {
  declare module.exports: any;
}

declare module 'jstree/src/vakata-jstree' {
  declare module.exports: any;
}

declare module 'jstree/test/unit/libs/qunit' {
  declare module.exports: any;
}

declare module 'jstree/test/unit/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jstree/dist/jstree.js' {
  declare module.exports: $Exports<'jstree/dist/jstree'>;
}
declare module 'jstree/dist/jstree.min.js' {
  declare module.exports: $Exports<'jstree/dist/jstree.min'>;
}
declare module 'jstree/gruntfile.js' {
  declare module.exports: $Exports<'jstree/gruntfile'>;
}
declare module 'jstree/src/intro.js' {
  declare module.exports: $Exports<'jstree/src/intro'>;
}
declare module 'jstree/src/jstree.changed.js' {
  declare module.exports: $Exports<'jstree/src/jstree.changed'>;
}
declare module 'jstree/src/jstree.checkbox.js' {
  declare module.exports: $Exports<'jstree/src/jstree.checkbox'>;
}
declare module 'jstree/src/jstree.conditionalselect.js' {
  declare module.exports: $Exports<'jstree/src/jstree.conditionalselect'>;
}
declare module 'jstree/src/jstree.contextmenu.js' {
  declare module.exports: $Exports<'jstree/src/jstree.contextmenu'>;
}
declare module 'jstree/src/jstree.dnd.js' {
  declare module.exports: $Exports<'jstree/src/jstree.dnd'>;
}
declare module 'jstree/src/jstree.js' {
  declare module.exports: $Exports<'jstree/src/jstree'>;
}
declare module 'jstree/src/jstree.massload.js' {
  declare module.exports: $Exports<'jstree/src/jstree.massload'>;
}
declare module 'jstree/src/jstree.search.js' {
  declare module.exports: $Exports<'jstree/src/jstree.search'>;
}
declare module 'jstree/src/jstree.sort.js' {
  declare module.exports: $Exports<'jstree/src/jstree.sort'>;
}
declare module 'jstree/src/jstree.state.js' {
  declare module.exports: $Exports<'jstree/src/jstree.state'>;
}
declare module 'jstree/src/jstree.types.js' {
  declare module.exports: $Exports<'jstree/src/jstree.types'>;
}
declare module 'jstree/src/jstree.unique.js' {
  declare module.exports: $Exports<'jstree/src/jstree.unique'>;
}
declare module 'jstree/src/jstree.wholerow.js' {
  declare module.exports: $Exports<'jstree/src/jstree.wholerow'>;
}
declare module 'jstree/src/misc.js' {
  declare module.exports: $Exports<'jstree/src/misc'>;
}
declare module 'jstree/src/outro.js' {
  declare module.exports: $Exports<'jstree/src/outro'>;
}
declare module 'jstree/src/sample.js' {
  declare module.exports: $Exports<'jstree/src/sample'>;
}
declare module 'jstree/src/vakata-jstree.js' {
  declare module.exports: $Exports<'jstree/src/vakata-jstree'>;
}
declare module 'jstree/test/unit/libs/qunit.js' {
  declare module.exports: $Exports<'jstree/test/unit/libs/qunit'>;
}
declare module 'jstree/test/unit/test.js' {
  declare module.exports: $Exports<'jstree/test/unit/test'>;
}
