// flow-typed signature: b3f929425df342ef3a39f5f6e7556a52
// flow-typed version: <<STUB>>/minivents_v^2.0.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minivents'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'minivents' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'minivents/dist/minivents.amd' {
  declare module.exports: any;
}

declare module 'minivents/dist/minivents.amd.min' {
  declare module.exports: any;
}

declare module 'minivents/dist/minivents.commonjs' {
  declare module.exports: any;
}

declare module 'minivents/dist/minivents.commonjs.min' {
  declare module.exports: any;
}

declare module 'minivents/dist/minivents' {
  declare module.exports: any;
}

declare module 'minivents/dist/minivents.min' {
  declare module.exports: any;
}

declare module 'minivents/gulpfile' {
  declare module.exports: any;
}

declare module 'minivents/src/minivents' {
  declare module.exports: any;
}

declare module 'minivents/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'minivents/dist/minivents.amd.js' {
  declare module.exports: $Exports<'minivents/dist/minivents.amd'>;
}
declare module 'minivents/dist/minivents.amd.min.js' {
  declare module.exports: $Exports<'minivents/dist/minivents.amd.min'>;
}
declare module 'minivents/dist/minivents.commonjs.js' {
  declare module.exports: $Exports<'minivents/dist/minivents.commonjs'>;
}
declare module 'minivents/dist/minivents.commonjs.min.js' {
  declare module.exports: $Exports<'minivents/dist/minivents.commonjs.min'>;
}
declare module 'minivents/dist/minivents.js' {
  declare module.exports: $Exports<'minivents/dist/minivents'>;
}
declare module 'minivents/dist/minivents.min.js' {
  declare module.exports: $Exports<'minivents/dist/minivents.min'>;
}
declare module 'minivents/gulpfile.js' {
  declare module.exports: $Exports<'minivents/gulpfile'>;
}
declare module 'minivents/src/minivents.js' {
  declare module.exports: $Exports<'minivents/src/minivents'>;
}
declare module 'minivents/test.js' {
  declare module.exports: $Exports<'minivents/test'>;
}
