// flow-typed signature: d58c8088d5876bdd82b4678d543c5633
// flow-typed version: <<STUB>>/nouislider_v^7.0.10/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nouislider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nouislider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nouislider/distribute/jquery.nouislider.all' {
  declare module.exports: any;
}

declare module 'nouislider/distribute/jquery.nouislider.all.min' {
  declare module.exports: any;
}

declare module 'nouislider/distribute/jquery.nouislider' {
  declare module.exports: any;
}

declare module 'nouislider/distribute/jquery.nouislider.min' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/behaviour-option/behaviour-option' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/behaviour-option/combined' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/behaviour-option/drag-fixed' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/behaviour-option/drag' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/behaviour-option/snap' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/behaviour-option/tap' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/events-callbacks/bind' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/events-callbacks/binding-events' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/events-callbacks/demo' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/events-callbacks/pass' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/colorpicker-setcolor' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/colorpicker-slider' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/date-helpers' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/date-link' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/date-setup' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/date-timestamp' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/html5-append' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/html5-link' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/html5-slider' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/keypress-event' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/keypress-slider' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/locked-crossupdate' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/locked-event' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/locked-link' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/locked-setup' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/locked-sliders' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/nonlinear-link' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/nonlinear-slider' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/skipstep-link' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/skipstep-slider' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/slider-soft-setup' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/slider-soft' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/toggle' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/tooltip-more' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/tooltip-simple' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/examples/tooltip' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/index/minimal' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/index/showcase' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/linking-input-fields/button' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/linking-input-fields/link-lower' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/linking-input-fields/link-upper' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/linking-input-fields/link' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/linking-input-fields/slider' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/more/disable-all' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/more/disable' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/more/options' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/more/update-setup' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/more/update' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/pips/a-slider-range-used' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/pips/count-slider' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/pips/count-stepped-slider' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/pips/count-stepped' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/pips/count' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/pips/positions-slider' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/pips/positions-stepped-slider' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/pips/positions-stepped' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/pips/positions' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/pips/range-slider' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/pips/range' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/pips/steps-slider' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/pips/steps' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/pips/values-slider' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/pips/values-stepped-slider' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/pips/values-stepped' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/pips/values' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-options/animate' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-options/connect' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-options/direction-link' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-options/direction' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-options/limit-link' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-options/limit' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-options/margin-link' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-options/margin' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-options/orientation' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-options/start' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-options/step' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-read-write/buttons' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-read-write/format' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-read-write/linkformat' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-read-write/read' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-read-write/set' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-read-write/wnumb' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-read-write/write' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-values/handles' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-values/non-linear-link' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-values/non-linear-step-link' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-values/non-linear-step' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-values/non-linear' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-values/range-link' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-values/range' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-values/snap-link' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-values/snap' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-values/step-link' {
  declare module.exports: any;
}

declare module 'nouislider/documentation/slider-values/step' {
  declare module.exports: any;
}

declare module 'nouislider/Gruntfile' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/constants' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/helpers' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/helpers/intro' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/helpers/outro' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/interface' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/options' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/pips' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/range' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/scope_end' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/scope_events' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/scope_helpers' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/scope_link' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/scope_start' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/scope' {
  declare module.exports: any;
}

declare module 'nouislider/src/js/structure' {
  declare module.exports: any;
}

declare module 'nouislider/tests/addon_pips' {
  declare module.exports: any;
}

declare module 'nouislider/tests/general_val' {
  declare module.exports: any;
}

declare module 'nouislider/tests/link_basic' {
  declare module.exports: any;
}

declare module 'nouislider/tests/link_multiple' {
  declare module.exports: any;
}

declare module 'nouislider/tests/link_rtl' {
  declare module.exports: any;
}

declare module 'nouislider/tests/link_select' {
  declare module.exports: any;
}

declare module 'nouislider/tests/link_update' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_events' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_get-step' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_limit' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_non-linear-rtl' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_none' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_rtl' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_setting-getting' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_step' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_unordered' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_update' {
  declare module.exports: any;
}

declare module 'nouislider/tests/slider_values' {
  declare module.exports: any;
}

declare module 'nouislider/tests/wnumb_basic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nouislider/distribute/jquery.nouislider.all.js' {
  declare module.exports: $Exports<'nouislider/distribute/jquery.nouislider.all'>;
}
declare module 'nouislider/distribute/jquery.nouislider.all.min.js' {
  declare module.exports: $Exports<'nouislider/distribute/jquery.nouislider.all.min'>;
}
declare module 'nouislider/distribute/jquery.nouislider.js' {
  declare module.exports: $Exports<'nouislider/distribute/jquery.nouislider'>;
}
declare module 'nouislider/distribute/jquery.nouislider.min.js' {
  declare module.exports: $Exports<'nouislider/distribute/jquery.nouislider.min'>;
}
declare module 'nouislider/documentation/behaviour-option/behaviour-option.js' {
  declare module.exports: $Exports<'nouislider/documentation/behaviour-option/behaviour-option'>;
}
declare module 'nouislider/documentation/behaviour-option/combined.js' {
  declare module.exports: $Exports<'nouislider/documentation/behaviour-option/combined'>;
}
declare module 'nouislider/documentation/behaviour-option/drag-fixed.js' {
  declare module.exports: $Exports<'nouislider/documentation/behaviour-option/drag-fixed'>;
}
declare module 'nouislider/documentation/behaviour-option/drag.js' {
  declare module.exports: $Exports<'nouislider/documentation/behaviour-option/drag'>;
}
declare module 'nouislider/documentation/behaviour-option/snap.js' {
  declare module.exports: $Exports<'nouislider/documentation/behaviour-option/snap'>;
}
declare module 'nouislider/documentation/behaviour-option/tap.js' {
  declare module.exports: $Exports<'nouislider/documentation/behaviour-option/tap'>;
}
declare module 'nouislider/documentation/events-callbacks/bind.js' {
  declare module.exports: $Exports<'nouislider/documentation/events-callbacks/bind'>;
}
declare module 'nouislider/documentation/events-callbacks/binding-events.js' {
  declare module.exports: $Exports<'nouislider/documentation/events-callbacks/binding-events'>;
}
declare module 'nouislider/documentation/events-callbacks/demo.js' {
  declare module.exports: $Exports<'nouislider/documentation/events-callbacks/demo'>;
}
declare module 'nouislider/documentation/events-callbacks/pass.js' {
  declare module.exports: $Exports<'nouislider/documentation/events-callbacks/pass'>;
}
declare module 'nouislider/documentation/examples/colorpicker-setcolor.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/colorpicker-setcolor'>;
}
declare module 'nouislider/documentation/examples/colorpicker-slider.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/colorpicker-slider'>;
}
declare module 'nouislider/documentation/examples/date-helpers.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/date-helpers'>;
}
declare module 'nouislider/documentation/examples/date-link.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/date-link'>;
}
declare module 'nouislider/documentation/examples/date-setup.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/date-setup'>;
}
declare module 'nouislider/documentation/examples/date-timestamp.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/date-timestamp'>;
}
declare module 'nouislider/documentation/examples/html5-append.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/html5-append'>;
}
declare module 'nouislider/documentation/examples/html5-link.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/html5-link'>;
}
declare module 'nouislider/documentation/examples/html5-slider.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/html5-slider'>;
}
declare module 'nouislider/documentation/examples/keypress-event.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/keypress-event'>;
}
declare module 'nouislider/documentation/examples/keypress-slider.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/keypress-slider'>;
}
declare module 'nouislider/documentation/examples/locked-crossupdate.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/locked-crossupdate'>;
}
declare module 'nouislider/documentation/examples/locked-event.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/locked-event'>;
}
declare module 'nouislider/documentation/examples/locked-link.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/locked-link'>;
}
declare module 'nouislider/documentation/examples/locked-setup.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/locked-setup'>;
}
declare module 'nouislider/documentation/examples/locked-sliders.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/locked-sliders'>;
}
declare module 'nouislider/documentation/examples/nonlinear-link.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/nonlinear-link'>;
}
declare module 'nouislider/documentation/examples/nonlinear-slider.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/nonlinear-slider'>;
}
declare module 'nouislider/documentation/examples/skipstep-link.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/skipstep-link'>;
}
declare module 'nouislider/documentation/examples/skipstep-slider.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/skipstep-slider'>;
}
declare module 'nouislider/documentation/examples/slider-soft-setup.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/slider-soft-setup'>;
}
declare module 'nouislider/documentation/examples/slider-soft.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/slider-soft'>;
}
declare module 'nouislider/documentation/examples/toggle.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/toggle'>;
}
declare module 'nouislider/documentation/examples/tooltip-more.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/tooltip-more'>;
}
declare module 'nouislider/documentation/examples/tooltip-simple.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/tooltip-simple'>;
}
declare module 'nouislider/documentation/examples/tooltip.js' {
  declare module.exports: $Exports<'nouislider/documentation/examples/tooltip'>;
}
declare module 'nouislider/documentation/index/minimal.js' {
  declare module.exports: $Exports<'nouislider/documentation/index/minimal'>;
}
declare module 'nouislider/documentation/index/showcase.js' {
  declare module.exports: $Exports<'nouislider/documentation/index/showcase'>;
}
declare module 'nouislider/documentation/linking-input-fields/button.js' {
  declare module.exports: $Exports<'nouislider/documentation/linking-input-fields/button'>;
}
declare module 'nouislider/documentation/linking-input-fields/link-lower.js' {
  declare module.exports: $Exports<'nouislider/documentation/linking-input-fields/link-lower'>;
}
declare module 'nouislider/documentation/linking-input-fields/link-upper.js' {
  declare module.exports: $Exports<'nouislider/documentation/linking-input-fields/link-upper'>;
}
declare module 'nouislider/documentation/linking-input-fields/link.js' {
  declare module.exports: $Exports<'nouislider/documentation/linking-input-fields/link'>;
}
declare module 'nouislider/documentation/linking-input-fields/slider.js' {
  declare module.exports: $Exports<'nouislider/documentation/linking-input-fields/slider'>;
}
declare module 'nouislider/documentation/more/disable-all.js' {
  declare module.exports: $Exports<'nouislider/documentation/more/disable-all'>;
}
declare module 'nouislider/documentation/more/disable.js' {
  declare module.exports: $Exports<'nouislider/documentation/more/disable'>;
}
declare module 'nouislider/documentation/more/options.js' {
  declare module.exports: $Exports<'nouislider/documentation/more/options'>;
}
declare module 'nouislider/documentation/more/update-setup.js' {
  declare module.exports: $Exports<'nouislider/documentation/more/update-setup'>;
}
declare module 'nouislider/documentation/more/update.js' {
  declare module.exports: $Exports<'nouislider/documentation/more/update'>;
}
declare module 'nouislider/documentation/pips/a-slider-range-used.js' {
  declare module.exports: $Exports<'nouislider/documentation/pips/a-slider-range-used'>;
}
declare module 'nouislider/documentation/pips/count-slider.js' {
  declare module.exports: $Exports<'nouislider/documentation/pips/count-slider'>;
}
declare module 'nouislider/documentation/pips/count-stepped-slider.js' {
  declare module.exports: $Exports<'nouislider/documentation/pips/count-stepped-slider'>;
}
declare module 'nouislider/documentation/pips/count-stepped.js' {
  declare module.exports: $Exports<'nouislider/documentation/pips/count-stepped'>;
}
declare module 'nouislider/documentation/pips/count.js' {
  declare module.exports: $Exports<'nouislider/documentation/pips/count'>;
}
declare module 'nouislider/documentation/pips/positions-slider.js' {
  declare module.exports: $Exports<'nouislider/documentation/pips/positions-slider'>;
}
declare module 'nouislider/documentation/pips/positions-stepped-slider.js' {
  declare module.exports: $Exports<'nouislider/documentation/pips/positions-stepped-slider'>;
}
declare module 'nouislider/documentation/pips/positions-stepped.js' {
  declare module.exports: $Exports<'nouislider/documentation/pips/positions-stepped'>;
}
declare module 'nouislider/documentation/pips/positions.js' {
  declare module.exports: $Exports<'nouislider/documentation/pips/positions'>;
}
declare module 'nouislider/documentation/pips/range-slider.js' {
  declare module.exports: $Exports<'nouislider/documentation/pips/range-slider'>;
}
declare module 'nouislider/documentation/pips/range.js' {
  declare module.exports: $Exports<'nouislider/documentation/pips/range'>;
}
declare module 'nouislider/documentation/pips/steps-slider.js' {
  declare module.exports: $Exports<'nouislider/documentation/pips/steps-slider'>;
}
declare module 'nouislider/documentation/pips/steps.js' {
  declare module.exports: $Exports<'nouislider/documentation/pips/steps'>;
}
declare module 'nouislider/documentation/pips/values-slider.js' {
  declare module.exports: $Exports<'nouislider/documentation/pips/values-slider'>;
}
declare module 'nouislider/documentation/pips/values-stepped-slider.js' {
  declare module.exports: $Exports<'nouislider/documentation/pips/values-stepped-slider'>;
}
declare module 'nouislider/documentation/pips/values-stepped.js' {
  declare module.exports: $Exports<'nouislider/documentation/pips/values-stepped'>;
}
declare module 'nouislider/documentation/pips/values.js' {
  declare module.exports: $Exports<'nouislider/documentation/pips/values'>;
}
declare module 'nouislider/documentation/slider-options/animate.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-options/animate'>;
}
declare module 'nouislider/documentation/slider-options/connect.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-options/connect'>;
}
declare module 'nouislider/documentation/slider-options/direction-link.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-options/direction-link'>;
}
declare module 'nouislider/documentation/slider-options/direction.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-options/direction'>;
}
declare module 'nouislider/documentation/slider-options/limit-link.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-options/limit-link'>;
}
declare module 'nouislider/documentation/slider-options/limit.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-options/limit'>;
}
declare module 'nouislider/documentation/slider-options/margin-link.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-options/margin-link'>;
}
declare module 'nouislider/documentation/slider-options/margin.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-options/margin'>;
}
declare module 'nouislider/documentation/slider-options/orientation.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-options/orientation'>;
}
declare module 'nouislider/documentation/slider-options/start.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-options/start'>;
}
declare module 'nouislider/documentation/slider-options/step.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-options/step'>;
}
declare module 'nouislider/documentation/slider-read-write/buttons.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-read-write/buttons'>;
}
declare module 'nouislider/documentation/slider-read-write/format.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-read-write/format'>;
}
declare module 'nouislider/documentation/slider-read-write/linkformat.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-read-write/linkformat'>;
}
declare module 'nouislider/documentation/slider-read-write/read.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-read-write/read'>;
}
declare module 'nouislider/documentation/slider-read-write/set.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-read-write/set'>;
}
declare module 'nouislider/documentation/slider-read-write/wnumb.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-read-write/wnumb'>;
}
declare module 'nouislider/documentation/slider-read-write/write.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-read-write/write'>;
}
declare module 'nouislider/documentation/slider-values/handles.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-values/handles'>;
}
declare module 'nouislider/documentation/slider-values/non-linear-link.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-values/non-linear-link'>;
}
declare module 'nouislider/documentation/slider-values/non-linear-step-link.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-values/non-linear-step-link'>;
}
declare module 'nouislider/documentation/slider-values/non-linear-step.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-values/non-linear-step'>;
}
declare module 'nouislider/documentation/slider-values/non-linear.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-values/non-linear'>;
}
declare module 'nouislider/documentation/slider-values/range-link.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-values/range-link'>;
}
declare module 'nouislider/documentation/slider-values/range.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-values/range'>;
}
declare module 'nouislider/documentation/slider-values/snap-link.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-values/snap-link'>;
}
declare module 'nouislider/documentation/slider-values/snap.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-values/snap'>;
}
declare module 'nouislider/documentation/slider-values/step-link.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-values/step-link'>;
}
declare module 'nouislider/documentation/slider-values/step.js' {
  declare module.exports: $Exports<'nouislider/documentation/slider-values/step'>;
}
declare module 'nouislider/Gruntfile.js' {
  declare module.exports: $Exports<'nouislider/Gruntfile'>;
}
declare module 'nouislider/src/js/constants.js' {
  declare module.exports: $Exports<'nouislider/src/js/constants'>;
}
declare module 'nouislider/src/js/helpers.js' {
  declare module.exports: $Exports<'nouislider/src/js/helpers'>;
}
declare module 'nouislider/src/js/helpers/intro.js' {
  declare module.exports: $Exports<'nouislider/src/js/helpers/intro'>;
}
declare module 'nouislider/src/js/helpers/outro.js' {
  declare module.exports: $Exports<'nouislider/src/js/helpers/outro'>;
}
declare module 'nouislider/src/js/interface.js' {
  declare module.exports: $Exports<'nouislider/src/js/interface'>;
}
declare module 'nouislider/src/js/options.js' {
  declare module.exports: $Exports<'nouislider/src/js/options'>;
}
declare module 'nouislider/src/js/pips.js' {
  declare module.exports: $Exports<'nouislider/src/js/pips'>;
}
declare module 'nouislider/src/js/range.js' {
  declare module.exports: $Exports<'nouislider/src/js/range'>;
}
declare module 'nouislider/src/js/scope_end.js' {
  declare module.exports: $Exports<'nouislider/src/js/scope_end'>;
}
declare module 'nouislider/src/js/scope_events.js' {
  declare module.exports: $Exports<'nouislider/src/js/scope_events'>;
}
declare module 'nouislider/src/js/scope_helpers.js' {
  declare module.exports: $Exports<'nouislider/src/js/scope_helpers'>;
}
declare module 'nouislider/src/js/scope_link.js' {
  declare module.exports: $Exports<'nouislider/src/js/scope_link'>;
}
declare module 'nouislider/src/js/scope_start.js' {
  declare module.exports: $Exports<'nouislider/src/js/scope_start'>;
}
declare module 'nouislider/src/js/scope.js' {
  declare module.exports: $Exports<'nouislider/src/js/scope'>;
}
declare module 'nouislider/src/js/structure.js' {
  declare module.exports: $Exports<'nouislider/src/js/structure'>;
}
declare module 'nouislider/tests/addon_pips.js' {
  declare module.exports: $Exports<'nouislider/tests/addon_pips'>;
}
declare module 'nouislider/tests/general_val.js' {
  declare module.exports: $Exports<'nouislider/tests/general_val'>;
}
declare module 'nouislider/tests/link_basic.js' {
  declare module.exports: $Exports<'nouislider/tests/link_basic'>;
}
declare module 'nouislider/tests/link_multiple.js' {
  declare module.exports: $Exports<'nouislider/tests/link_multiple'>;
}
declare module 'nouislider/tests/link_rtl.js' {
  declare module.exports: $Exports<'nouislider/tests/link_rtl'>;
}
declare module 'nouislider/tests/link_select.js' {
  declare module.exports: $Exports<'nouislider/tests/link_select'>;
}
declare module 'nouislider/tests/link_update.js' {
  declare module.exports: $Exports<'nouislider/tests/link_update'>;
}
declare module 'nouislider/tests/slider_events.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_events'>;
}
declare module 'nouislider/tests/slider_get-step.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_get-step'>;
}
declare module 'nouislider/tests/slider_limit.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_limit'>;
}
declare module 'nouislider/tests/slider_non-linear-rtl.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_non-linear-rtl'>;
}
declare module 'nouislider/tests/slider_none.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_none'>;
}
declare module 'nouislider/tests/slider_rtl.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_rtl'>;
}
declare module 'nouislider/tests/slider_setting-getting.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_setting-getting'>;
}
declare module 'nouislider/tests/slider_step.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_step'>;
}
declare module 'nouislider/tests/slider_unordered.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_unordered'>;
}
declare module 'nouislider/tests/slider_update.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_update'>;
}
declare module 'nouislider/tests/slider_values.js' {
  declare module.exports: $Exports<'nouislider/tests/slider_values'>;
}
declare module 'nouislider/tests/wnumb_basic.js' {
  declare module.exports: $Exports<'nouislider/tests/wnumb_basic'>;
}
