// flow-typed signature: 32251ebd3b8a4240d207e39647426a64
// flow-typed version: <<STUB>>/payform_v^1.2.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'payform'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'payform' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'payform/dist/jquery.payform' {
  declare module.exports: any;
}

declare module 'payform/dist/jquery.payform.min' {
  declare module.exports: any;
}

declare module 'payform/dist/payform' {
  declare module.exports: any;
}

declare module 'payform/dist/payform.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'payform/dist/jquery.payform.js' {
  declare module.exports: $Exports<'payform/dist/jquery.payform'>;
}
declare module 'payform/dist/jquery.payform.min.js' {
  declare module.exports: $Exports<'payform/dist/jquery.payform.min'>;
}
declare module 'payform/dist/payform.js' {
  declare module.exports: $Exports<'payform/dist/payform'>;
}
declare module 'payform/dist/payform.min.js' {
  declare module.exports: $Exports<'payform/dist/payform.min'>;
}
