// flow-typed signature: f4de76257b9b9a0fa3577d082e5b3f8c
// flow-typed version: <<STUB>>/photoswipe_v^4.1.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'photoswipe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'photoswipe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'photoswipe/dist/photoswipe-ui-default' {
  declare module.exports: any;
}

declare module 'photoswipe/dist/photoswipe-ui-default.min' {
  declare module.exports: any;
}

declare module 'photoswipe/dist/photoswipe' {
  declare module.exports: any;
}

declare module 'photoswipe/dist/photoswipe.min' {
  declare module.exports: any;
}

declare module 'photoswipe/Gruntfile' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/core' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/desktop-zoom' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/framework-bridge' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/gestures' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/history' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/items-controller' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/show-hide-transition' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/tap' {
  declare module.exports: any;
}

declare module 'photoswipe/src/js/ui/photoswipe-ui-default' {
  declare module.exports: any;
}

// Filename aliases
declare module 'photoswipe/dist/photoswipe-ui-default.js' {
  declare module.exports: $Exports<'photoswipe/dist/photoswipe-ui-default'>;
}
declare module 'photoswipe/dist/photoswipe-ui-default.min.js' {
  declare module.exports: $Exports<'photoswipe/dist/photoswipe-ui-default.min'>;
}
declare module 'photoswipe/dist/photoswipe.js' {
  declare module.exports: $Exports<'photoswipe/dist/photoswipe'>;
}
declare module 'photoswipe/dist/photoswipe.min.js' {
  declare module.exports: $Exports<'photoswipe/dist/photoswipe.min'>;
}
declare module 'photoswipe/Gruntfile.js' {
  declare module.exports: $Exports<'photoswipe/Gruntfile'>;
}
declare module 'photoswipe/src/js/core.js' {
  declare module.exports: $Exports<'photoswipe/src/js/core'>;
}
declare module 'photoswipe/src/js/desktop-zoom.js' {
  declare module.exports: $Exports<'photoswipe/src/js/desktop-zoom'>;
}
declare module 'photoswipe/src/js/framework-bridge.js' {
  declare module.exports: $Exports<'photoswipe/src/js/framework-bridge'>;
}
declare module 'photoswipe/src/js/gestures.js' {
  declare module.exports: $Exports<'photoswipe/src/js/gestures'>;
}
declare module 'photoswipe/src/js/history.js' {
  declare module.exports: $Exports<'photoswipe/src/js/history'>;
}
declare module 'photoswipe/src/js/items-controller.js' {
  declare module.exports: $Exports<'photoswipe/src/js/items-controller'>;
}
declare module 'photoswipe/src/js/show-hide-transition.js' {
  declare module.exports: $Exports<'photoswipe/src/js/show-hide-transition'>;
}
declare module 'photoswipe/src/js/tap.js' {
  declare module.exports: $Exports<'photoswipe/src/js/tap'>;
}
declare module 'photoswipe/src/js/ui/photoswipe-ui-default.js' {
  declare module.exports: $Exports<'photoswipe/src/js/ui/photoswipe-ui-default'>;
}
