// flow-typed signature: d9db06eb089c8ab105ffbeaa67771ffe
// flow-typed version: <<STUB>>/pure-css-loader_v^2.2.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pure-css-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pure-css-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pure-css-loader/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pure-css-loader/gulpfile.js' {
  declare module.exports: $Exports<'pure-css-loader/gulpfile'>;
}
