// flow-typed signature: 3a3c2b71d9fa6e670696f4ae3a86da77
// flow-typed version: <<STUB>>/raty-js_v^2.7.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raty-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'raty-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'raty-js/demo/javascripts/labs' {
  declare module.exports: any;
}

declare module 'raty-js/lib/jquery.raty' {
  declare module.exports: any;
}

declare module 'raty-js/spec/cancel_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/cancelhint_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/cancelon_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/cancelplace_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/click_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/common_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/fn_cancel_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/fn_move_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/fn_readonly_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/fn_set_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/fn_setscore_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/getfirstdecimal_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/half_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/hints_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/karma.conf' {
  declare module.exports: any;
}

declare module 'raty-js/spec/lib/boot' {
  declare module.exports: any;
}

declare module 'raty-js/spec/lib/helper' {
  declare module.exports: any;
}

declare module 'raty-js/spec/lib/jasmine-html' {
  declare module.exports: any;
}

declare module 'raty-js/spec/lib/jasmine-jquery' {
  declare module.exports: any;
}

declare module 'raty-js/spec/lib/jasmine' {
  declare module.exports: any;
}

declare module 'raty-js/spec/mouseout_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/mouseover_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/number_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/numbermax_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/options_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/path_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/precision_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/readonly_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/score_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/scorename_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/staroff_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/staron_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/stars_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/startype_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/target_spec' {
  declare module.exports: any;
}

declare module 'raty-js/spec/targettype_spec' {
  declare module.exports: any;
}

declare module 'raty-js/vendor/jquery' {
  declare module.exports: any;
}

// Filename aliases
declare module 'raty-js/demo/javascripts/labs.js' {
  declare module.exports: $Exports<'raty-js/demo/javascripts/labs'>;
}
declare module 'raty-js/lib/jquery.raty.js' {
  declare module.exports: $Exports<'raty-js/lib/jquery.raty'>;
}
declare module 'raty-js/spec/cancel_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/cancel_spec'>;
}
declare module 'raty-js/spec/cancelhint_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/cancelhint_spec'>;
}
declare module 'raty-js/spec/cancelon_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/cancelon_spec'>;
}
declare module 'raty-js/spec/cancelplace_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/cancelplace_spec'>;
}
declare module 'raty-js/spec/click_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/click_spec'>;
}
declare module 'raty-js/spec/common_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/common_spec'>;
}
declare module 'raty-js/spec/fn_cancel_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/fn_cancel_spec'>;
}
declare module 'raty-js/spec/fn_move_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/fn_move_spec'>;
}
declare module 'raty-js/spec/fn_readonly_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/fn_readonly_spec'>;
}
declare module 'raty-js/spec/fn_set_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/fn_set_spec'>;
}
declare module 'raty-js/spec/fn_setscore_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/fn_setscore_spec'>;
}
declare module 'raty-js/spec/getfirstdecimal_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/getfirstdecimal_spec'>;
}
declare module 'raty-js/spec/half_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/half_spec'>;
}
declare module 'raty-js/spec/hints_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/hints_spec'>;
}
declare module 'raty-js/spec/karma.conf.js' {
  declare module.exports: $Exports<'raty-js/spec/karma.conf'>;
}
declare module 'raty-js/spec/lib/boot.js' {
  declare module.exports: $Exports<'raty-js/spec/lib/boot'>;
}
declare module 'raty-js/spec/lib/helper.js' {
  declare module.exports: $Exports<'raty-js/spec/lib/helper'>;
}
declare module 'raty-js/spec/lib/jasmine-html.js' {
  declare module.exports: $Exports<'raty-js/spec/lib/jasmine-html'>;
}
declare module 'raty-js/spec/lib/jasmine-jquery.js' {
  declare module.exports: $Exports<'raty-js/spec/lib/jasmine-jquery'>;
}
declare module 'raty-js/spec/lib/jasmine.js' {
  declare module.exports: $Exports<'raty-js/spec/lib/jasmine'>;
}
declare module 'raty-js/spec/mouseout_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/mouseout_spec'>;
}
declare module 'raty-js/spec/mouseover_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/mouseover_spec'>;
}
declare module 'raty-js/spec/number_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/number_spec'>;
}
declare module 'raty-js/spec/numbermax_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/numbermax_spec'>;
}
declare module 'raty-js/spec/options_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/options_spec'>;
}
declare module 'raty-js/spec/path_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/path_spec'>;
}
declare module 'raty-js/spec/precision_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/precision_spec'>;
}
declare module 'raty-js/spec/readonly_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/readonly_spec'>;
}
declare module 'raty-js/spec/score_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/score_spec'>;
}
declare module 'raty-js/spec/scorename_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/scorename_spec'>;
}
declare module 'raty-js/spec/spec.js' {
  declare module.exports: $Exports<'raty-js/spec/spec'>;
}
declare module 'raty-js/spec/staroff_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/staroff_spec'>;
}
declare module 'raty-js/spec/staron_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/staron_spec'>;
}
declare module 'raty-js/spec/stars_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/stars_spec'>;
}
declare module 'raty-js/spec/startype_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/startype_spec'>;
}
declare module 'raty-js/spec/target_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/target_spec'>;
}
declare module 'raty-js/spec/targettype_spec.js' {
  declare module.exports: $Exports<'raty-js/spec/targettype_spec'>;
}
declare module 'raty-js/vendor/jquery.js' {
  declare module.exports: $Exports<'raty-js/vendor/jquery'>;
}
