// flow-typed signature: 21fc7a825c2e097b1c3165273344768e
// flow-typed version: <<STUB>>/raygun4js_v^2.5.3/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raygun4js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'raygun4js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'raygun4js/dist/raygun' {
  declare module.exports: any;
}

declare module 'raygun4js/dist/raygun.min' {
  declare module.exports: any;
}

declare module 'raygun4js/dist/raygun.umd' {
  declare module.exports: any;
}

declare module 'raygun4js/dist/raygun.umd.min' {
  declare module.exports: any;
}

declare module 'raygun4js/dist/raygun.vanilla' {
  declare module.exports: any;
}

declare module 'raygun4js/dist/raygun.vanilla.min' {
  declare module.exports: any;
}

declare module 'raygun4js/Gruntfile' {
  declare module.exports: any;
}

declare module 'raygun4js/src/raygun' {
  declare module.exports: any;
}

declare module 'raygun4js/src/raygun.js-url' {
  declare module.exports: any;
}

declare module 'raygun4js/src/raygun.loader' {
  declare module.exports: any;
}

declare module 'raygun4js/src/raygun.rum' {
  declare module.exports: any;
}

declare module 'raygun4js/src/raygun.tracekit.jquery' {
  declare module.exports: any;
}

declare module 'raygun4js/src/snippet/minified' {
  declare module.exports: any;
}

declare module 'raygun4js/src/snippet/minified.nohandler' {
  declare module.exports: any;
}

declare module 'raygun4js/src/snippet/unminified' {
  declare module.exports: any;
}

declare module 'raygun4js/src/snippet/unminified.nohandler' {
  declare module.exports: any;
}

declare module 'raygun4js/src/umd.intro' {
  declare module.exports: any;
}

declare module 'raygun4js/src/umd.outro' {
  declare module.exports: any;
}

declare module 'raygun4js/tests/fixtures/common/instrumentXHRs' {
  declare module.exports: any;
}

declare module 'raygun4js/tests/specs/v1/basic' {
  declare module.exports: any;
}

declare module 'raygun4js/tests/specs/v1/eventsXhr' {
  declare module.exports: any;
}

declare module 'raygun4js/tests/specs/v1/payloadManualSendTests' {
  declare module.exports: any;
}

declare module 'raygun4js/tests/specs/v1/payloadUnhandledErrorTests' {
  declare module.exports: any;
}

declare module 'raygun4js/tests/specs/v2/basic' {
  declare module.exports: any;
}

declare module 'raygun4js/tests/specs/v2/eventsXhr' {
  declare module.exports: any;
}

declare module 'raygun4js/tests/specs/v2/payloadManualSendTests' {
  declare module.exports: any;
}

declare module 'raygun4js/tests/specs/v2/payloadSyntaxError' {
  declare module.exports: any;
}

declare module 'raygun4js/tests/specs/v2/payloadUnhandledErrorTests' {
  declare module.exports: any;
}

declare module 'raygun4js/tests/specs/v2/rg4jsLoaderTests' {
  declare module.exports: any;
}

declare module 'raygun4js/tracekit/grunt' {
  declare module.exports: any;
}

declare module 'raygun4js/tracekit/tests/mocha' {
  declare module.exports: any;
}

declare module 'raygun4js/tracekit/tracekit' {
  declare module.exports: any;
}

declare module 'raygun4js/wdio.conf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'raygun4js/dist/raygun.js' {
  declare module.exports: $Exports<'raygun4js/dist/raygun'>;
}
declare module 'raygun4js/dist/raygun.min.js' {
  declare module.exports: $Exports<'raygun4js/dist/raygun.min'>;
}
declare module 'raygun4js/dist/raygun.umd.js' {
  declare module.exports: $Exports<'raygun4js/dist/raygun.umd'>;
}
declare module 'raygun4js/dist/raygun.umd.min.js' {
  declare module.exports: $Exports<'raygun4js/dist/raygun.umd.min'>;
}
declare module 'raygun4js/dist/raygun.vanilla.js' {
  declare module.exports: $Exports<'raygun4js/dist/raygun.vanilla'>;
}
declare module 'raygun4js/dist/raygun.vanilla.min.js' {
  declare module.exports: $Exports<'raygun4js/dist/raygun.vanilla.min'>;
}
declare module 'raygun4js/Gruntfile.js' {
  declare module.exports: $Exports<'raygun4js/Gruntfile'>;
}
declare module 'raygun4js/src/raygun.js' {
  declare module.exports: $Exports<'raygun4js/src/raygun'>;
}
declare module 'raygun4js/src/raygun.js-url.js' {
  declare module.exports: $Exports<'raygun4js/src/raygun.js-url'>;
}
declare module 'raygun4js/src/raygun.loader.js' {
  declare module.exports: $Exports<'raygun4js/src/raygun.loader'>;
}
declare module 'raygun4js/src/raygun.rum.js' {
  declare module.exports: $Exports<'raygun4js/src/raygun.rum'>;
}
declare module 'raygun4js/src/raygun.tracekit.jquery.js' {
  declare module.exports: $Exports<'raygun4js/src/raygun.tracekit.jquery'>;
}
declare module 'raygun4js/src/snippet/minified.js' {
  declare module.exports: $Exports<'raygun4js/src/snippet/minified'>;
}
declare module 'raygun4js/src/snippet/minified.nohandler.js' {
  declare module.exports: $Exports<'raygun4js/src/snippet/minified.nohandler'>;
}
declare module 'raygun4js/src/snippet/unminified.js' {
  declare module.exports: $Exports<'raygun4js/src/snippet/unminified'>;
}
declare module 'raygun4js/src/snippet/unminified.nohandler.js' {
  declare module.exports: $Exports<'raygun4js/src/snippet/unminified.nohandler'>;
}
declare module 'raygun4js/src/umd.intro.js' {
  declare module.exports: $Exports<'raygun4js/src/umd.intro'>;
}
declare module 'raygun4js/src/umd.outro.js' {
  declare module.exports: $Exports<'raygun4js/src/umd.outro'>;
}
declare module 'raygun4js/tests/fixtures/common/instrumentXHRs.js' {
  declare module.exports: $Exports<'raygun4js/tests/fixtures/common/instrumentXHRs'>;
}
declare module 'raygun4js/tests/specs/v1/basic.js' {
  declare module.exports: $Exports<'raygun4js/tests/specs/v1/basic'>;
}
declare module 'raygun4js/tests/specs/v1/eventsXhr.js' {
  declare module.exports: $Exports<'raygun4js/tests/specs/v1/eventsXhr'>;
}
declare module 'raygun4js/tests/specs/v1/payloadManualSendTests.js' {
  declare module.exports: $Exports<'raygun4js/tests/specs/v1/payloadManualSendTests'>;
}
declare module 'raygun4js/tests/specs/v1/payloadUnhandledErrorTests.js' {
  declare module.exports: $Exports<'raygun4js/tests/specs/v1/payloadUnhandledErrorTests'>;
}
declare module 'raygun4js/tests/specs/v2/basic.js' {
  declare module.exports: $Exports<'raygun4js/tests/specs/v2/basic'>;
}
declare module 'raygun4js/tests/specs/v2/eventsXhr.js' {
  declare module.exports: $Exports<'raygun4js/tests/specs/v2/eventsXhr'>;
}
declare module 'raygun4js/tests/specs/v2/payloadManualSendTests.js' {
  declare module.exports: $Exports<'raygun4js/tests/specs/v2/payloadManualSendTests'>;
}
declare module 'raygun4js/tests/specs/v2/payloadSyntaxError.js' {
  declare module.exports: $Exports<'raygun4js/tests/specs/v2/payloadSyntaxError'>;
}
declare module 'raygun4js/tests/specs/v2/payloadUnhandledErrorTests.js' {
  declare module.exports: $Exports<'raygun4js/tests/specs/v2/payloadUnhandledErrorTests'>;
}
declare module 'raygun4js/tests/specs/v2/rg4jsLoaderTests.js' {
  declare module.exports: $Exports<'raygun4js/tests/specs/v2/rg4jsLoaderTests'>;
}
declare module 'raygun4js/tracekit/grunt.js' {
  declare module.exports: $Exports<'raygun4js/tracekit/grunt'>;
}
declare module 'raygun4js/tracekit/tests/mocha.js' {
  declare module.exports: $Exports<'raygun4js/tracekit/tests/mocha'>;
}
declare module 'raygun4js/tracekit/tracekit.js' {
  declare module.exports: $Exports<'raygun4js/tracekit/tracekit'>;
}
declare module 'raygun4js/wdio.conf.js' {
  declare module.exports: $Exports<'raygun4js/wdio.conf'>;
}
