// flow-typed signature: 4cc71bfa95897d387376704ac4e83bfd
// flow-typed version: <<STUB>>/select2_v^3.5.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'select2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'select2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'select2/select2_locale_ar' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_az' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_bg' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_ca' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_cs' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_da' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_de' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_el' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_es' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_et' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_eu' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_fa' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_fi' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_fr' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_gl' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_he' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_hr' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_hu' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_id' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_is' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_it' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_ja' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_ka' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_ko' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_lt' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_lv' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_mk' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_ms' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_nl' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_no' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_pl' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_pt-BR' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_pt-PT' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_ro' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_rs' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_ru' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_sk' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_sv' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_th' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_tr' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_ug-CN' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_uk' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_vi' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_zh-CN' {
  declare module.exports: any;
}

declare module 'select2/select2_locale_zh-TW' {
  declare module.exports: any;
}

declare module 'select2/select2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'select2/select2_locale_ar.js' {
  declare module.exports: $Exports<'select2/select2_locale_ar'>;
}
declare module 'select2/select2_locale_az.js' {
  declare module.exports: $Exports<'select2/select2_locale_az'>;
}
declare module 'select2/select2_locale_bg.js' {
  declare module.exports: $Exports<'select2/select2_locale_bg'>;
}
declare module 'select2/select2_locale_ca.js' {
  declare module.exports: $Exports<'select2/select2_locale_ca'>;
}
declare module 'select2/select2_locale_cs.js' {
  declare module.exports: $Exports<'select2/select2_locale_cs'>;
}
declare module 'select2/select2_locale_da.js' {
  declare module.exports: $Exports<'select2/select2_locale_da'>;
}
declare module 'select2/select2_locale_de.js' {
  declare module.exports: $Exports<'select2/select2_locale_de'>;
}
declare module 'select2/select2_locale_el.js' {
  declare module.exports: $Exports<'select2/select2_locale_el'>;
}
declare module 'select2/select2_locale_es.js' {
  declare module.exports: $Exports<'select2/select2_locale_es'>;
}
declare module 'select2/select2_locale_et.js' {
  declare module.exports: $Exports<'select2/select2_locale_et'>;
}
declare module 'select2/select2_locale_eu.js' {
  declare module.exports: $Exports<'select2/select2_locale_eu'>;
}
declare module 'select2/select2_locale_fa.js' {
  declare module.exports: $Exports<'select2/select2_locale_fa'>;
}
declare module 'select2/select2_locale_fi.js' {
  declare module.exports: $Exports<'select2/select2_locale_fi'>;
}
declare module 'select2/select2_locale_fr.js' {
  declare module.exports: $Exports<'select2/select2_locale_fr'>;
}
declare module 'select2/select2_locale_gl.js' {
  declare module.exports: $Exports<'select2/select2_locale_gl'>;
}
declare module 'select2/select2_locale_he.js' {
  declare module.exports: $Exports<'select2/select2_locale_he'>;
}
declare module 'select2/select2_locale_hr.js' {
  declare module.exports: $Exports<'select2/select2_locale_hr'>;
}
declare module 'select2/select2_locale_hu.js' {
  declare module.exports: $Exports<'select2/select2_locale_hu'>;
}
declare module 'select2/select2_locale_id.js' {
  declare module.exports: $Exports<'select2/select2_locale_id'>;
}
declare module 'select2/select2_locale_is.js' {
  declare module.exports: $Exports<'select2/select2_locale_is'>;
}
declare module 'select2/select2_locale_it.js' {
  declare module.exports: $Exports<'select2/select2_locale_it'>;
}
declare module 'select2/select2_locale_ja.js' {
  declare module.exports: $Exports<'select2/select2_locale_ja'>;
}
declare module 'select2/select2_locale_ka.js' {
  declare module.exports: $Exports<'select2/select2_locale_ka'>;
}
declare module 'select2/select2_locale_ko.js' {
  declare module.exports: $Exports<'select2/select2_locale_ko'>;
}
declare module 'select2/select2_locale_lt.js' {
  declare module.exports: $Exports<'select2/select2_locale_lt'>;
}
declare module 'select2/select2_locale_lv.js' {
  declare module.exports: $Exports<'select2/select2_locale_lv'>;
}
declare module 'select2/select2_locale_mk.js' {
  declare module.exports: $Exports<'select2/select2_locale_mk'>;
}
declare module 'select2/select2_locale_ms.js' {
  declare module.exports: $Exports<'select2/select2_locale_ms'>;
}
declare module 'select2/select2_locale_nl.js' {
  declare module.exports: $Exports<'select2/select2_locale_nl'>;
}
declare module 'select2/select2_locale_no.js' {
  declare module.exports: $Exports<'select2/select2_locale_no'>;
}
declare module 'select2/select2_locale_pl.js' {
  declare module.exports: $Exports<'select2/select2_locale_pl'>;
}
declare module 'select2/select2_locale_pt-BR.js' {
  declare module.exports: $Exports<'select2/select2_locale_pt-BR'>;
}
declare module 'select2/select2_locale_pt-PT.js' {
  declare module.exports: $Exports<'select2/select2_locale_pt-PT'>;
}
declare module 'select2/select2_locale_ro.js' {
  declare module.exports: $Exports<'select2/select2_locale_ro'>;
}
declare module 'select2/select2_locale_rs.js' {
  declare module.exports: $Exports<'select2/select2_locale_rs'>;
}
declare module 'select2/select2_locale_ru.js' {
  declare module.exports: $Exports<'select2/select2_locale_ru'>;
}
declare module 'select2/select2_locale_sk.js' {
  declare module.exports: $Exports<'select2/select2_locale_sk'>;
}
declare module 'select2/select2_locale_sv.js' {
  declare module.exports: $Exports<'select2/select2_locale_sv'>;
}
declare module 'select2/select2_locale_th.js' {
  declare module.exports: $Exports<'select2/select2_locale_th'>;
}
declare module 'select2/select2_locale_tr.js' {
  declare module.exports: $Exports<'select2/select2_locale_tr'>;
}
declare module 'select2/select2_locale_ug-CN.js' {
  declare module.exports: $Exports<'select2/select2_locale_ug-CN'>;
}
declare module 'select2/select2_locale_uk.js' {
  declare module.exports: $Exports<'select2/select2_locale_uk'>;
}
declare module 'select2/select2_locale_vi.js' {
  declare module.exports: $Exports<'select2/select2_locale_vi'>;
}
declare module 'select2/select2_locale_zh-CN.js' {
  declare module.exports: $Exports<'select2/select2_locale_zh-CN'>;
}
declare module 'select2/select2_locale_zh-TW.js' {
  declare module.exports: $Exports<'select2/select2_locale_zh-TW'>;
}
declare module 'select2/select2.js' {
  declare module.exports: $Exports<'select2/select2'>;
}
