// flow-typed signature: f697d0acf9b6e8c587266e5b3f98a659
// flow-typed version: <<STUB>>/spin.js_v^2.3.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spin.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'spin.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spin.js/jquery.spin' {
  declare module.exports: any;
}

declare module 'spin.js/spin' {
  declare module.exports: any;
}

declare module 'spin.js/spin.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spin.js/jquery.spin.js' {
  declare module.exports: $Exports<'spin.js/jquery.spin'>;
}
declare module 'spin.js/spin.js' {
  declare module.exports: $Exports<'spin.js/spin'>;
}
declare module 'spin.js/spin.min.js' {
  declare module.exports: $Exports<'spin.js/spin.min'>;
}
