// flow-typed signature: 9ea0667d455277de7ad304a4aa2ad07c
// flow-typed version: <<STUB>>/svgxuse_v^1.2.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svgxuse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'svgxuse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svgxuse/svgxuse' {
  declare module.exports: any;
}

declare module 'svgxuse/svgxuse.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svgxuse/svgxuse.js' {
  declare module.exports: $Exports<'svgxuse/svgxuse'>;
}
declare module 'svgxuse/svgxuse.min.js' {
  declare module.exports: $Exports<'svgxuse/svgxuse.min'>;
}
