// flow-typed signature: cc23b37313866949322d776e30e8b3b3
// flow-typed version: <<STUB>>/swipebox_v^1.4.6/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swipebox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'swipebox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swipebox/grunt/gruntfile' {
  declare module.exports: any;
}

declare module 'swipebox/lib/ios-orientationchange-fix' {
  declare module.exports: any;
}

declare module 'swipebox/lib/jquery-2.1.0.min' {
  declare module.exports: any;
}

declare module 'swipebox/src/js/jquery.swipebox' {
  declare module.exports: any;
}

declare module 'swipebox/src/js/jquery.swipebox.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swipebox/grunt/gruntfile.js' {
  declare module.exports: $Exports<'swipebox/grunt/gruntfile'>;
}
declare module 'swipebox/lib/ios-orientationchange-fix.js' {
  declare module.exports: $Exports<'swipebox/lib/ios-orientationchange-fix'>;
}
declare module 'swipebox/lib/jquery-2.1.0.min.js' {
  declare module.exports: $Exports<'swipebox/lib/jquery-2.1.0.min'>;
}
declare module 'swipebox/src/js/jquery.swipebox.js' {
  declare module.exports: $Exports<'swipebox/src/js/jquery.swipebox'>;
}
declare module 'swipebox/src/js/jquery.swipebox.min.js' {
  declare module.exports: $Exports<'swipebox/src/js/jquery.swipebox.min'>;
}
