// flow-typed signature: 57f22a2968bc6a94156c1740f5acea16
// flow-typed version: <<STUB>>/timepicker_v^1.11.9/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timepicker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'timepicker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'timepicker/GruntFile' {
  declare module.exports: any;
}

declare module 'timepicker/jquery.timepicker' {
  declare module.exports: any;
}

declare module 'timepicker/jquery.timepicker.min' {
  declare module.exports: any;
}

declare module 'timepicker/lib/bootstrap-datepicker' {
  declare module.exports: any;
}

declare module 'timepicker/lib/site' {
  declare module.exports: any;
}

// Filename aliases
declare module 'timepicker/GruntFile.js' {
  declare module.exports: $Exports<'timepicker/GruntFile'>;
}
declare module 'timepicker/jquery.timepicker.js' {
  declare module.exports: $Exports<'timepicker/jquery.timepicker'>;
}
declare module 'timepicker/jquery.timepicker.min.js' {
  declare module.exports: $Exports<'timepicker/jquery.timepicker.min'>;
}
declare module 'timepicker/lib/bootstrap-datepicker.js' {
  declare module.exports: $Exports<'timepicker/lib/bootstrap-datepicker'>;
}
declare module 'timepicker/lib/site.js' {
  declare module.exports: $Exports<'timepicker/lib/site'>;
}
