// flow-typed signature: 3927bce34a2c7dd610a2ad22098137e9
// flow-typed version: <<STUB>>/urlify_v^0.3.6/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'urlify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'urlify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'urlify/dist/urlify-dev' {
  declare module.exports: any;
}

declare module 'urlify/dist/urlify' {
  declare module.exports: any;
}

declare module 'urlify/lib/urlify' {
  declare module.exports: any;
}

declare module 'urlify/test/common' {
  declare module.exports: any;
}

declare module 'urlify/test/main' {
  declare module.exports: any;
}

declare module 'urlify/test/support/jquery' {
  declare module.exports: any;
}

// Filename aliases
declare module 'urlify/dist/urlify-dev.js' {
  declare module.exports: $Exports<'urlify/dist/urlify-dev'>;
}
declare module 'urlify/dist/urlify.js' {
  declare module.exports: $Exports<'urlify/dist/urlify'>;
}
declare module 'urlify/index' {
  declare module.exports: $Exports<'urlify'>;
}
declare module 'urlify/index.js' {
  declare module.exports: $Exports<'urlify'>;
}
declare module 'urlify/lib/urlify.js' {
  declare module.exports: $Exports<'urlify/lib/urlify'>;
}
declare module 'urlify/test/common.js' {
  declare module.exports: $Exports<'urlify/test/common'>;
}
declare module 'urlify/test/main.js' {
  declare module.exports: $Exports<'urlify/test/main'>;
}
declare module 'urlify/test/support/jquery.js' {
  declare module.exports: $Exports<'urlify/test/support/jquery'>;
}
