// flow-typed signature: c442198a55634b05e53435e4c417f559
// flow-typed version: <<STUB>>/vinyl-paths_v^2.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vinyl-paths'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vinyl-paths' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'vinyl-paths/index' {
  declare module.exports: $Exports<'vinyl-paths'>;
}
declare module 'vinyl-paths/index.js' {
  declare module.exports: $Exports<'vinyl-paths'>;
}
