// flow-typed signature: 4d0ff2e059eebb2188aa4a5f99c68720
// flow-typed version: <<STUB>>/x-editable_v^1.5.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'x-editable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'x-editable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'x-editable/dist/bootstrap-editable/js/bootstrap-editable' {
  declare module.exports: any;
}

declare module 'x-editable/dist/bootstrap-editable/js/bootstrap-editable.min' {
  declare module.exports: any;
}

declare module 'x-editable/dist/bootstrap3-editable/js/bootstrap-editable' {
  declare module.exports: any;
}

declare module 'x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min' {
  declare module.exports: any;
}

declare module 'x-editable/dist/inputs-ext/address/address' {
  declare module.exports: any;
}

declare module 'x-editable/dist/inputs-ext/typeaheadjs/lib/typeahead' {
  declare module.exports: any;
}

declare module 'x-editable/dist/inputs-ext/typeaheadjs/typeaheadjs' {
  declare module.exports: any;
}

declare module 'x-editable/dist/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/bootstrap-wysihtml5-0.0.2' {
  declare module.exports: any;
}

declare module 'x-editable/dist/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/bootstrap-wysihtml5-0.0.2.min' {
  declare module.exports: any;
}

declare module 'x-editable/dist/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/wysihtml5-0.3.0' {
  declare module.exports: any;
}

declare module 'x-editable/dist/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/wysihtml5-0.3.0.min' {
  declare module.exports: any;
}

declare module 'x-editable/dist/inputs-ext/wysihtml5/wysihtml5' {
  declare module.exports: any;
}

declare module 'x-editable/dist/jquery-editable/jquery-ui-datepicker/js/jquery-ui-1.10.3.custom' {
  declare module.exports: any;
}

declare module 'x-editable/dist/jquery-editable/jquery-ui-datepicker/js/jquery-ui-1.10.3.custom.min' {
  declare module.exports: any;
}

declare module 'x-editable/dist/jquery-editable/js/jquery-editable-poshytip' {
  declare module.exports: any;
}

declare module 'x-editable/dist/jquery-editable/js/jquery-editable-poshytip.min' {
  declare module.exports: any;
}

declare module 'x-editable/dist/jqueryui-editable/js/jqueryui-editable' {
  declare module.exports: any;
}

declare module 'x-editable/dist/jqueryui-editable/js/jqueryui-editable.min' {
  declare module.exports: any;
}

declare module 'x-editable/Gruntfile' {
  declare module.exports: any;
}

declare module 'x-editable/src/containers/editable-container' {
  declare module.exports: any;
}

declare module 'x-editable/src/containers/editable-inline' {
  declare module.exports: any;
}

declare module 'x-editable/src/containers/editable-popover' {
  declare module.exports: any;
}

declare module 'x-editable/src/containers/editable-popover3' {
  declare module.exports: any;
}

declare module 'x-editable/src/containers/editable-poshytip' {
  declare module.exports: any;
}

declare module 'x-editable/src/containers/editable-tooltip' {
  declare module.exports: any;
}

declare module 'x-editable/src/editable-form/editable-form-bootstrap' {
  declare module.exports: any;
}

declare module 'x-editable/src/editable-form/editable-form-bootstrap3' {
  declare module.exports: any;
}

declare module 'x-editable/src/editable-form/editable-form-jqueryui' {
  declare module.exports: any;
}

declare module 'x-editable/src/editable-form/editable-form-utils' {
  declare module.exports: any;
}

declare module 'x-editable/src/editable-form/editable-form' {
  declare module.exports: any;
}

declare module 'x-editable/src/element/editable-element' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs-ext/address/address' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs-ext/typeaheadjs/lib/typeahead' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs-ext/typeaheadjs/typeaheadjs' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/bootstrap-wysihtml5-0.0.2' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/bootstrap-wysihtml5-0.0.2.min' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/wysihtml5-0.3.0' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/wysihtml5-0.3.0.min' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs-ext/wysihtml5/wysihtml5' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/abstract' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/checklist' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/combodate/combodate' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/combodate/lib/combodate' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/combodate/lib/moment.min.1.7.2' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/combodate/lib/moment.min' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/date/bootstrap-datepicker/js/bootstrap-datepicker' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/date/date' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/date/datefield' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/datetime/bootstrap-datetimepicker/js/bootstrap-datetimepicker' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/datetime/datetime' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/datetime/datetimefield' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/dateui/dateui' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/dateui/dateuifield' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.10.1.custom' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.10.1.custom.min' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.10.2.custom' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.10.2.custom.min' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.10.3.custom' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.10.3.custom.min' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.9.1.custom' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.9.1.custom.min' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/html5types' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/list' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/select' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/select2/lib/select2' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/select2/lib/select2.min' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/select2/select2' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/text' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/textarea' {
  declare module.exports: any;
}

declare module 'x-editable/src/inputs/typeahead' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/bootstrap221/js/bootstrap' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/bootstrap221/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/bootstrap222/js/bootstrap' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/bootstrap222/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/bootstrap231/js/bootstrap' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/bootstrap231/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/bootstrap232/js/bootstrap' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/bootstrap232/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/bootstrap300/js/bootstrap' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/bootstrap300/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/jquery-ui-1.10.1.custom/js/jquery-1.9.1' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/jquery-ui-1.10.1.custom/js/jquery-ui-1.10.1.custom' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/jquery-ui-1.10.1.custom/js/jquery-ui-1.10.1.custom.min' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/jquery-ui-1.10.2.custom/js/jquery-1.9.1' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/jquery-ui-1.10.2.custom/js/jquery-ui-1.10.2.custom' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/jquery-ui-1.10.2.custom/js/jquery-ui-1.10.2.custom.min' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/jquery-ui-1.10.3.custom/js/jquery-1.9.1' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/jquery-ui-1.9.1.custom/jquery.ui.datepicker-ru' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/jquery-ui-1.9.1.custom/js/jquery-1.8.2' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/jquery-ui-1.9.1.custom/js/jquery-ui-1.9.1.custom' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/jquery-ui-1.9.1.custom/js/jquery-ui-1.9.1.custom.min' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/jquery/jquery-1.8.2' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/jquery/jquery-1.8.2.min' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/jquery/jquery-1.9.0.min' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/jquery/jquery-1.9.1' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/jquery/jquery-1.9.1.min' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/mockjax/jquery.mockjax' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/poshytip/jquery.poshytip' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/poshytip/jquery.poshytip.min' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/qunit/qunit-1.10.0' {
  declare module.exports: any;
}

declare module 'x-editable/test/libs/qunit/qunit-1.12.0' {
  declare module.exports: any;
}

declare module 'x-editable/test/loader' {
  declare module.exports: any;
}

declare module 'x-editable/test/main' {
  declare module.exports: any;
}

declare module 'x-editable/test/mocks' {
  declare module.exports: any;
}

declare module 'x-editable/test/require' {
  declare module.exports: any;
}

declare module 'x-editable/test/unit/api' {
  declare module.exports: any;
}

declare module 'x-editable/test/unit/checklist' {
  declare module.exports: any;
}

declare module 'x-editable/test/unit/combodate' {
  declare module.exports: any;
}

declare module 'x-editable/test/unit/common' {
  declare module.exports: any;
}

declare module 'x-editable/test/unit/date' {
  declare module.exports: any;
}

declare module 'x-editable/test/unit/datefield' {
  declare module.exports: any;
}

declare module 'x-editable/test/unit/datetime' {
  declare module.exports: any;
}

declare module 'x-editable/test/unit/datetimefield' {
  declare module.exports: any;
}

declare module 'x-editable/test/unit/dateui' {
  declare module.exports: any;
}

declare module 'x-editable/test/unit/dateuifield' {
  declare module.exports: any;
}

declare module 'x-editable/test/unit/select' {
  declare module.exports: any;
}

declare module 'x-editable/test/unit/select2' {
  declare module.exports: any;
}

declare module 'x-editable/test/unit/text' {
  declare module.exports: any;
}

declare module 'x-editable/test/unit/textarea' {
  declare module.exports: any;
}

declare module 'x-editable/test/unit/typeahead' {
  declare module.exports: any;
}

declare module 'x-editable/test/unit/typeaheadjs' {
  declare module.exports: any;
}

declare module 'x-editable/test/unit/wysihtml5' {
  declare module.exports: any;
}

// Filename aliases
declare module 'x-editable/dist/bootstrap-editable/js/bootstrap-editable.js' {
  declare module.exports: $Exports<'x-editable/dist/bootstrap-editable/js/bootstrap-editable'>;
}
declare module 'x-editable/dist/bootstrap-editable/js/bootstrap-editable.min.js' {
  declare module.exports: $Exports<'x-editable/dist/bootstrap-editable/js/bootstrap-editable.min'>;
}
declare module 'x-editable/dist/bootstrap3-editable/js/bootstrap-editable.js' {
  declare module.exports: $Exports<'x-editable/dist/bootstrap3-editable/js/bootstrap-editable'>;
}
declare module 'x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js' {
  declare module.exports: $Exports<'x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min'>;
}
declare module 'x-editable/dist/inputs-ext/address/address.js' {
  declare module.exports: $Exports<'x-editable/dist/inputs-ext/address/address'>;
}
declare module 'x-editable/dist/inputs-ext/typeaheadjs/lib/typeahead.js' {
  declare module.exports: $Exports<'x-editable/dist/inputs-ext/typeaheadjs/lib/typeahead'>;
}
declare module 'x-editable/dist/inputs-ext/typeaheadjs/typeaheadjs.js' {
  declare module.exports: $Exports<'x-editable/dist/inputs-ext/typeaheadjs/typeaheadjs'>;
}
declare module 'x-editable/dist/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/bootstrap-wysihtml5-0.0.2.js' {
  declare module.exports: $Exports<'x-editable/dist/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/bootstrap-wysihtml5-0.0.2'>;
}
declare module 'x-editable/dist/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/bootstrap-wysihtml5-0.0.2.min.js' {
  declare module.exports: $Exports<'x-editable/dist/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/bootstrap-wysihtml5-0.0.2.min'>;
}
declare module 'x-editable/dist/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/wysihtml5-0.3.0.js' {
  declare module.exports: $Exports<'x-editable/dist/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/wysihtml5-0.3.0'>;
}
declare module 'x-editable/dist/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/wysihtml5-0.3.0.min.js' {
  declare module.exports: $Exports<'x-editable/dist/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/wysihtml5-0.3.0.min'>;
}
declare module 'x-editable/dist/inputs-ext/wysihtml5/wysihtml5.js' {
  declare module.exports: $Exports<'x-editable/dist/inputs-ext/wysihtml5/wysihtml5'>;
}
declare module 'x-editable/dist/jquery-editable/jquery-ui-datepicker/js/jquery-ui-1.10.3.custom.js' {
  declare module.exports: $Exports<'x-editable/dist/jquery-editable/jquery-ui-datepicker/js/jquery-ui-1.10.3.custom'>;
}
declare module 'x-editable/dist/jquery-editable/jquery-ui-datepicker/js/jquery-ui-1.10.3.custom.min.js' {
  declare module.exports: $Exports<'x-editable/dist/jquery-editable/jquery-ui-datepicker/js/jquery-ui-1.10.3.custom.min'>;
}
declare module 'x-editable/dist/jquery-editable/js/jquery-editable-poshytip.js' {
  declare module.exports: $Exports<'x-editable/dist/jquery-editable/js/jquery-editable-poshytip'>;
}
declare module 'x-editable/dist/jquery-editable/js/jquery-editable-poshytip.min.js' {
  declare module.exports: $Exports<'x-editable/dist/jquery-editable/js/jquery-editable-poshytip.min'>;
}
declare module 'x-editable/dist/jqueryui-editable/js/jqueryui-editable.js' {
  declare module.exports: $Exports<'x-editable/dist/jqueryui-editable/js/jqueryui-editable'>;
}
declare module 'x-editable/dist/jqueryui-editable/js/jqueryui-editable.min.js' {
  declare module.exports: $Exports<'x-editable/dist/jqueryui-editable/js/jqueryui-editable.min'>;
}
declare module 'x-editable/Gruntfile.js' {
  declare module.exports: $Exports<'x-editable/Gruntfile'>;
}
declare module 'x-editable/src/containers/editable-container.js' {
  declare module.exports: $Exports<'x-editable/src/containers/editable-container'>;
}
declare module 'x-editable/src/containers/editable-inline.js' {
  declare module.exports: $Exports<'x-editable/src/containers/editable-inline'>;
}
declare module 'x-editable/src/containers/editable-popover.js' {
  declare module.exports: $Exports<'x-editable/src/containers/editable-popover'>;
}
declare module 'x-editable/src/containers/editable-popover3.js' {
  declare module.exports: $Exports<'x-editable/src/containers/editable-popover3'>;
}
declare module 'x-editable/src/containers/editable-poshytip.js' {
  declare module.exports: $Exports<'x-editable/src/containers/editable-poshytip'>;
}
declare module 'x-editable/src/containers/editable-tooltip.js' {
  declare module.exports: $Exports<'x-editable/src/containers/editable-tooltip'>;
}
declare module 'x-editable/src/editable-form/editable-form-bootstrap.js' {
  declare module.exports: $Exports<'x-editable/src/editable-form/editable-form-bootstrap'>;
}
declare module 'x-editable/src/editable-form/editable-form-bootstrap3.js' {
  declare module.exports: $Exports<'x-editable/src/editable-form/editable-form-bootstrap3'>;
}
declare module 'x-editable/src/editable-form/editable-form-jqueryui.js' {
  declare module.exports: $Exports<'x-editable/src/editable-form/editable-form-jqueryui'>;
}
declare module 'x-editable/src/editable-form/editable-form-utils.js' {
  declare module.exports: $Exports<'x-editable/src/editable-form/editable-form-utils'>;
}
declare module 'x-editable/src/editable-form/editable-form.js' {
  declare module.exports: $Exports<'x-editable/src/editable-form/editable-form'>;
}
declare module 'x-editable/src/element/editable-element.js' {
  declare module.exports: $Exports<'x-editable/src/element/editable-element'>;
}
declare module 'x-editable/src/inputs-ext/address/address.js' {
  declare module.exports: $Exports<'x-editable/src/inputs-ext/address/address'>;
}
declare module 'x-editable/src/inputs-ext/typeaheadjs/lib/typeahead.js' {
  declare module.exports: $Exports<'x-editable/src/inputs-ext/typeaheadjs/lib/typeahead'>;
}
declare module 'x-editable/src/inputs-ext/typeaheadjs/typeaheadjs.js' {
  declare module.exports: $Exports<'x-editable/src/inputs-ext/typeaheadjs/typeaheadjs'>;
}
declare module 'x-editable/src/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/bootstrap-wysihtml5-0.0.2.js' {
  declare module.exports: $Exports<'x-editable/src/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/bootstrap-wysihtml5-0.0.2'>;
}
declare module 'x-editable/src/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/bootstrap-wysihtml5-0.0.2.min.js' {
  declare module.exports: $Exports<'x-editable/src/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/bootstrap-wysihtml5-0.0.2.min'>;
}
declare module 'x-editable/src/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/wysihtml5-0.3.0.js' {
  declare module.exports: $Exports<'x-editable/src/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/wysihtml5-0.3.0'>;
}
declare module 'x-editable/src/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/wysihtml5-0.3.0.min.js' {
  declare module.exports: $Exports<'x-editable/src/inputs-ext/wysihtml5/bootstrap-wysihtml5-0.0.2/wysihtml5-0.3.0.min'>;
}
declare module 'x-editable/src/inputs-ext/wysihtml5/wysihtml5.js' {
  declare module.exports: $Exports<'x-editable/src/inputs-ext/wysihtml5/wysihtml5'>;
}
declare module 'x-editable/src/inputs/abstract.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/abstract'>;
}
declare module 'x-editable/src/inputs/checklist.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/checklist'>;
}
declare module 'x-editable/src/inputs/combodate/combodate.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/combodate/combodate'>;
}
declare module 'x-editable/src/inputs/combodate/lib/combodate.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/combodate/lib/combodate'>;
}
declare module 'x-editable/src/inputs/combodate/lib/moment.min.1.7.2.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/combodate/lib/moment.min.1.7.2'>;
}
declare module 'x-editable/src/inputs/combodate/lib/moment.min.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/combodate/lib/moment.min'>;
}
declare module 'x-editable/src/inputs/date/bootstrap-datepicker/js/bootstrap-datepicker.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/date/bootstrap-datepicker/js/bootstrap-datepicker'>;
}
declare module 'x-editable/src/inputs/date/date.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/date/date'>;
}
declare module 'x-editable/src/inputs/date/datefield.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/date/datefield'>;
}
declare module 'x-editable/src/inputs/datetime/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/datetime/bootstrap-datetimepicker/js/bootstrap-datetimepicker'>;
}
declare module 'x-editable/src/inputs/datetime/datetime.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/datetime/datetime'>;
}
declare module 'x-editable/src/inputs/datetime/datetimefield.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/datetime/datetimefield'>;
}
declare module 'x-editable/src/inputs/dateui/dateui.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/dateui/dateui'>;
}
declare module 'x-editable/src/inputs/dateui/dateuifield.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/dateui/dateuifield'>;
}
declare module 'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.10.1.custom.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.10.1.custom'>;
}
declare module 'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.10.1.custom.min.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.10.1.custom.min'>;
}
declare module 'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.10.2.custom.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.10.2.custom'>;
}
declare module 'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.10.2.custom.min.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.10.2.custom.min'>;
}
declare module 'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.10.3.custom.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.10.3.custom'>;
}
declare module 'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.10.3.custom.min.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.10.3.custom.min'>;
}
declare module 'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.9.1.custom.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.9.1.custom'>;
}
declare module 'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.9.1.custom.min.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/dateui/jquery-ui-datepicker/js/jquery-ui-1.9.1.custom.min'>;
}
declare module 'x-editable/src/inputs/html5types.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/html5types'>;
}
declare module 'x-editable/src/inputs/list.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/list'>;
}
declare module 'x-editable/src/inputs/select.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/select'>;
}
declare module 'x-editable/src/inputs/select2/lib/select2.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/select2/lib/select2'>;
}
declare module 'x-editable/src/inputs/select2/lib/select2.min.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/select2/lib/select2.min'>;
}
declare module 'x-editable/src/inputs/select2/select2.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/select2/select2'>;
}
declare module 'x-editable/src/inputs/text.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/text'>;
}
declare module 'x-editable/src/inputs/textarea.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/textarea'>;
}
declare module 'x-editable/src/inputs/typeahead.js' {
  declare module.exports: $Exports<'x-editable/src/inputs/typeahead'>;
}
declare module 'x-editable/test/libs/bootstrap221/js/bootstrap.js' {
  declare module.exports: $Exports<'x-editable/test/libs/bootstrap221/js/bootstrap'>;
}
declare module 'x-editable/test/libs/bootstrap221/js/bootstrap.min.js' {
  declare module.exports: $Exports<'x-editable/test/libs/bootstrap221/js/bootstrap.min'>;
}
declare module 'x-editable/test/libs/bootstrap222/js/bootstrap.js' {
  declare module.exports: $Exports<'x-editable/test/libs/bootstrap222/js/bootstrap'>;
}
declare module 'x-editable/test/libs/bootstrap222/js/bootstrap.min.js' {
  declare module.exports: $Exports<'x-editable/test/libs/bootstrap222/js/bootstrap.min'>;
}
declare module 'x-editable/test/libs/bootstrap231/js/bootstrap.js' {
  declare module.exports: $Exports<'x-editable/test/libs/bootstrap231/js/bootstrap'>;
}
declare module 'x-editable/test/libs/bootstrap231/js/bootstrap.min.js' {
  declare module.exports: $Exports<'x-editable/test/libs/bootstrap231/js/bootstrap.min'>;
}
declare module 'x-editable/test/libs/bootstrap232/js/bootstrap.js' {
  declare module.exports: $Exports<'x-editable/test/libs/bootstrap232/js/bootstrap'>;
}
declare module 'x-editable/test/libs/bootstrap232/js/bootstrap.min.js' {
  declare module.exports: $Exports<'x-editable/test/libs/bootstrap232/js/bootstrap.min'>;
}
declare module 'x-editable/test/libs/bootstrap300/js/bootstrap.js' {
  declare module.exports: $Exports<'x-editable/test/libs/bootstrap300/js/bootstrap'>;
}
declare module 'x-editable/test/libs/bootstrap300/js/bootstrap.min.js' {
  declare module.exports: $Exports<'x-editable/test/libs/bootstrap300/js/bootstrap.min'>;
}
declare module 'x-editable/test/libs/jquery-ui-1.10.1.custom/js/jquery-1.9.1.js' {
  declare module.exports: $Exports<'x-editable/test/libs/jquery-ui-1.10.1.custom/js/jquery-1.9.1'>;
}
declare module 'x-editable/test/libs/jquery-ui-1.10.1.custom/js/jquery-ui-1.10.1.custom.js' {
  declare module.exports: $Exports<'x-editable/test/libs/jquery-ui-1.10.1.custom/js/jquery-ui-1.10.1.custom'>;
}
declare module 'x-editable/test/libs/jquery-ui-1.10.1.custom/js/jquery-ui-1.10.1.custom.min.js' {
  declare module.exports: $Exports<'x-editable/test/libs/jquery-ui-1.10.1.custom/js/jquery-ui-1.10.1.custom.min'>;
}
declare module 'x-editable/test/libs/jquery-ui-1.10.2.custom/js/jquery-1.9.1.js' {
  declare module.exports: $Exports<'x-editable/test/libs/jquery-ui-1.10.2.custom/js/jquery-1.9.1'>;
}
declare module 'x-editable/test/libs/jquery-ui-1.10.2.custom/js/jquery-ui-1.10.2.custom.js' {
  declare module.exports: $Exports<'x-editable/test/libs/jquery-ui-1.10.2.custom/js/jquery-ui-1.10.2.custom'>;
}
declare module 'x-editable/test/libs/jquery-ui-1.10.2.custom/js/jquery-ui-1.10.2.custom.min.js' {
  declare module.exports: $Exports<'x-editable/test/libs/jquery-ui-1.10.2.custom/js/jquery-ui-1.10.2.custom.min'>;
}
declare module 'x-editable/test/libs/jquery-ui-1.10.3.custom/js/jquery-1.9.1.js' {
  declare module.exports: $Exports<'x-editable/test/libs/jquery-ui-1.10.3.custom/js/jquery-1.9.1'>;
}
declare module 'x-editable/test/libs/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.js' {
  declare module.exports: $Exports<'x-editable/test/libs/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom'>;
}
declare module 'x-editable/test/libs/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.js' {
  declare module.exports: $Exports<'x-editable/test/libs/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min'>;
}
declare module 'x-editable/test/libs/jquery-ui-1.9.1.custom/jquery.ui.datepicker-ru.js' {
  declare module.exports: $Exports<'x-editable/test/libs/jquery-ui-1.9.1.custom/jquery.ui.datepicker-ru'>;
}
declare module 'x-editable/test/libs/jquery-ui-1.9.1.custom/js/jquery-1.8.2.js' {
  declare module.exports: $Exports<'x-editable/test/libs/jquery-ui-1.9.1.custom/js/jquery-1.8.2'>;
}
declare module 'x-editable/test/libs/jquery-ui-1.9.1.custom/js/jquery-ui-1.9.1.custom.js' {
  declare module.exports: $Exports<'x-editable/test/libs/jquery-ui-1.9.1.custom/js/jquery-ui-1.9.1.custom'>;
}
declare module 'x-editable/test/libs/jquery-ui-1.9.1.custom/js/jquery-ui-1.9.1.custom.min.js' {
  declare module.exports: $Exports<'x-editable/test/libs/jquery-ui-1.9.1.custom/js/jquery-ui-1.9.1.custom.min'>;
}
declare module 'x-editable/test/libs/jquery/jquery-1.8.2.js' {
  declare module.exports: $Exports<'x-editable/test/libs/jquery/jquery-1.8.2'>;
}
declare module 'x-editable/test/libs/jquery/jquery-1.8.2.min.js' {
  declare module.exports: $Exports<'x-editable/test/libs/jquery/jquery-1.8.2.min'>;
}
declare module 'x-editable/test/libs/jquery/jquery-1.9.0.min.js' {
  declare module.exports: $Exports<'x-editable/test/libs/jquery/jquery-1.9.0.min'>;
}
declare module 'x-editable/test/libs/jquery/jquery-1.9.1.js' {
  declare module.exports: $Exports<'x-editable/test/libs/jquery/jquery-1.9.1'>;
}
declare module 'x-editable/test/libs/jquery/jquery-1.9.1.min.js' {
  declare module.exports: $Exports<'x-editable/test/libs/jquery/jquery-1.9.1.min'>;
}
declare module 'x-editable/test/libs/mockjax/jquery.mockjax.js' {
  declare module.exports: $Exports<'x-editable/test/libs/mockjax/jquery.mockjax'>;
}
declare module 'x-editable/test/libs/poshytip/jquery.poshytip.js' {
  declare module.exports: $Exports<'x-editable/test/libs/poshytip/jquery.poshytip'>;
}
declare module 'x-editable/test/libs/poshytip/jquery.poshytip.min.js' {
  declare module.exports: $Exports<'x-editable/test/libs/poshytip/jquery.poshytip.min'>;
}
declare module 'x-editable/test/libs/qunit/qunit-1.10.0.js' {
  declare module.exports: $Exports<'x-editable/test/libs/qunit/qunit-1.10.0'>;
}
declare module 'x-editable/test/libs/qunit/qunit-1.12.0.js' {
  declare module.exports: $Exports<'x-editable/test/libs/qunit/qunit-1.12.0'>;
}
declare module 'x-editable/test/loader.js' {
  declare module.exports: $Exports<'x-editable/test/loader'>;
}
declare module 'x-editable/test/main.js' {
  declare module.exports: $Exports<'x-editable/test/main'>;
}
declare module 'x-editable/test/mocks.js' {
  declare module.exports: $Exports<'x-editable/test/mocks'>;
}
declare module 'x-editable/test/require.js' {
  declare module.exports: $Exports<'x-editable/test/require'>;
}
declare module 'x-editable/test/unit/api.js' {
  declare module.exports: $Exports<'x-editable/test/unit/api'>;
}
declare module 'x-editable/test/unit/checklist.js' {
  declare module.exports: $Exports<'x-editable/test/unit/checklist'>;
}
declare module 'x-editable/test/unit/combodate.js' {
  declare module.exports: $Exports<'x-editable/test/unit/combodate'>;
}
declare module 'x-editable/test/unit/common.js' {
  declare module.exports: $Exports<'x-editable/test/unit/common'>;
}
declare module 'x-editable/test/unit/date.js' {
  declare module.exports: $Exports<'x-editable/test/unit/date'>;
}
declare module 'x-editable/test/unit/datefield.js' {
  declare module.exports: $Exports<'x-editable/test/unit/datefield'>;
}
declare module 'x-editable/test/unit/datetime.js' {
  declare module.exports: $Exports<'x-editable/test/unit/datetime'>;
}
declare module 'x-editable/test/unit/datetimefield.js' {
  declare module.exports: $Exports<'x-editable/test/unit/datetimefield'>;
}
declare module 'x-editable/test/unit/dateui.js' {
  declare module.exports: $Exports<'x-editable/test/unit/dateui'>;
}
declare module 'x-editable/test/unit/dateuifield.js' {
  declare module.exports: $Exports<'x-editable/test/unit/dateuifield'>;
}
declare module 'x-editable/test/unit/select.js' {
  declare module.exports: $Exports<'x-editable/test/unit/select'>;
}
declare module 'x-editable/test/unit/select2.js' {
  declare module.exports: $Exports<'x-editable/test/unit/select2'>;
}
declare module 'x-editable/test/unit/text.js' {
  declare module.exports: $Exports<'x-editable/test/unit/text'>;
}
declare module 'x-editable/test/unit/textarea.js' {
  declare module.exports: $Exports<'x-editable/test/unit/textarea'>;
}
declare module 'x-editable/test/unit/typeahead.js' {
  declare module.exports: $Exports<'x-editable/test/unit/typeahead'>;
}
declare module 'x-editable/test/unit/typeaheadjs.js' {
  declare module.exports: $Exports<'x-editable/test/unit/typeaheadjs'>;
}
declare module 'x-editable/test/unit/wysihtml5.js' {
  declare module.exports: $Exports<'x-editable/test/unit/wysihtml5'>;
}
