module RatingConstants
  MAX_QUESTIONS_QUANTITY = 5
  MAX_RATING = 5
  VALID_VALUES = (1..MAX_QUESTIONS_QUANTITY)

  SELLER = 'seller'
  PRODUCT = 'product'
  BUYER = 'buyer'
  FEEDBACK_TYPES = [SELLER, PRODUCT, BUYER]

  HOST = 'host'
  TRANSACTABLE = 'transactable'
  GUEST = 'guest'
  RATING_SYSTEM_SUBJECTS = [HOST, TRANSACTABLE, GUEST]

  RATING_MAPPING = Hash[FEEDBACK_TYPES.zip(RATING_SYSTEM_SUBJECTS)].freeze
end