class UpdateIndustriesList < ActiveRecord::Migration
  def up
    connection.execute <<-SQL
      DELETE from  industries
    SQL
    connection.execute <<-SQL
      DELETE from company_industries
    SQL
    connection.execute <<-SQL
      INSERT INTO industries (name, created_at, updated_at) VALUES
       ('Accounting', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Airlines/Aviation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Alternative Dispute Resolution', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Alternative Medicine', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Animation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Apparel & Fashion', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Architecture & Planning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Arts and Crafts', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Automotive', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Aviation & Aerospace', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Banking', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Biotechnology', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Broadcast Media', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Building Materials', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Business Supplies and Equipment', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Capital Markets', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Chemicals', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Civic & Social Organization', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Civil Engineering', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Commercial Real Estate', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Computer & Network Security', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Computer Games', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Computer Hardware', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Computer Networking', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Computer Software', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Construction', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Consumer Electronics', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Consumer Goods', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Consumer Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Cosmetics', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Dairy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Defense & Space', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Design', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Education Management', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('E-Learning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Electrical/Electronic Manufacturing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Entertainment', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Environmental Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Events Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Executive Office', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Facilities Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Farming', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Financial Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Fine Art', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Fishery', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Food & Beverages', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Food Production', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Fund-Raising', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Furniture', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Gambling & Casinos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Glass, Ceramics & Concrete', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Government Administration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Government Relations', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Graphic Design', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Health, Wellness and Fitness', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Higher Education', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Hospital & Health Care', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Hospitality', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Human Resources', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Import and Export', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Individual & Family Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Industrial Automation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Information Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Information Technology and Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Insurance', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('International Affairs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('International Trade and Development', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Internet', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Investment Banking', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Investment Management', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Judiciary', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Law Enforcement', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Law Practice', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Legal Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Legislative Office', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Leisure, Travel & Tourism', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Libraries', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Logistics and Supply Chain', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Luxury Goods & Jewelry', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Machinery', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Management Consulting', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Maritime', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Marketing and Advertising', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Market Research', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Mechanical or Industrial Engineering', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Media Production', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Medical Devices', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Medical Practice', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Mental Health Care', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Military', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Mining & Metals', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Motion Pictures and Film', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Museums and Institutions', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Music', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Nanotechnology', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Newspapers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Nonprofit Organization Management', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Oil & Energy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Online Media', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Outsourcing/Offshoring', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Package/Freight Delivery', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Packaging and Containers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Paper & Forest Products', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Performing Arts', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Pharmaceuticals', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Philanthropy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Photography', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Plastics', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Political Organization', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Primary/Secondary Education', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Printing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Professional Training & Coaching', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Program Development', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Public Policy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Public Relations and Communications', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Public Safety', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Publishing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Railroad Manufacture', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Ranching', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Real Estate', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Recreational Facilities and Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Religious Institutions', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Renewables & Environment', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Research', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Restaurants', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Retail', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Security and Investigations', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Semiconductors', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Shipbuilding', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Sporting Goods', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Sports', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Staffing and Recruiting', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Supermarkets', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Telecommunications', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Textiles', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Think Tanks', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Tobacco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Translation and Localization', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Transportation/Trucking/Railroad', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Utilities', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Venture Capital & Private Equity', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Veterinary', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Warehousing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Wholesale', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Wine and Spirits', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Wireless', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Writing and Editing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    SQL
  end

  def self.down
    raise ActiveRecord::IrreversibleMigration
  end
end
