class DropSpree < ActiveRecord::Migration
  def up
    drop_table :spree_addresses
    drop_table :spree_adjustments
    drop_table :spree_assets
    drop_table :spree_calculators
    drop_table :spree_countries
    drop_table :spree_credit_cards
    drop_table :spree_customer_returns
    drop_table :spree_gateways
    drop_table :spree_inventory_units
    drop_table :spree_line_items
    drop_table :spree_log_entries
    drop_table :spree_option_types
    drop_table :spree_option_types_prototypes
    drop_table :spree_option_values
    drop_table :spree_orders
    drop_table :spree_product_types
    drop_table :spree_products
    drop_table :spree_orders_promotions
    drop_table :spree_payment_capture_events
    drop_table :spree_payment_methods
    drop_table :spree_payments
    drop_table :spree_preferences
    drop_table :spree_prices
    drop_table :spree_product_option_types
    drop_table :spree_product_properties
    drop_table :spree_products_promotion_rules
    drop_table :spree_products_taxons
    drop_table :spree_promotion_action_line_items
    drop_table :spree_promotion_actions
    drop_table :spree_promotion_categories
    drop_table :spree_promotion_rules
    drop_table :spree_promotion_rules_users
    drop_table :spree_promotions
    drop_table :spree_properties
    drop_table :spree_properties_prototypes
    drop_table :spree_prototypes
    drop_table :spree_refund_reasons
    drop_table :spree_refunds
    drop_table :spree_reimbursement_credits
    drop_table :spree_reimbursement_types
    drop_table :spree_reimbursements
    drop_table :spree_return_authorization_reasons
    drop_table :spree_return_authorizations
    drop_table :spree_return_items
    drop_table :spree_roles
    drop_table :spree_roles_users
    drop_table :spree_shipments
    drop_table :spree_shipping_categories
    drop_table :spree_shipping_method_categories
    drop_table :spree_shipping_methods
    drop_table :spree_shipping_methods_zones
    drop_table :spree_shipping_rates
    drop_table :spree_state_changes
    drop_table :spree_states
    drop_table :spree_stock_items
    drop_table :spree_stock_locations
    drop_table :spree_stock_movements
    drop_table :spree_stock_transfers
    drop_table :spree_stores
    drop_table :spree_tax_categories
    drop_table :spree_tax_rates
    drop_table :spree_taxonomies
    drop_table :spree_taxons
    drop_table :spree_taxons_promotion_rules
    drop_table :spree_taxons_prototypes
    drop_table :spree_trackers
    drop_table :spree_users
    drop_table :spree_variants
    drop_table :spree_zone_members
    drop_table :spree_zones
  end
end
